### ISSUE TITLE
Tool Crash

### ISSUE THREAD

**Issue by reconnization** [projectdiscovery/nuclei#3293] opened 2023-02-09 13:00 UTC
[INF] Current Version: 2.8.8
**nuclei -list subdomains.txt -nc > out.txt**

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb3a766]

goroutine 109888607 [running]:
github.com/antchfx/xpath.(*childQuery).Select(0xc014e07620, {0x28782a0, 0xc01298b3e0})
        github.com/antchfx/xpath@v1.2.2/query.go:202 +0x126
github.com/antchfx/xpath.(*childQuery).Select(0xc014e07950, {0x28782a0, 0xc01298b3e0})
        github.com/antchfx/xpath@v1.2.2/query.go:183 +0x62
github.com/antchfx/xpath.(*childQuery).Select(0xc014e079b0, {0x28782a0, 0xc01298b3e0})
        github.com/antchfx/xpath@v1.2.2/query.go:183 +0x62
github.com/antchfx/xpath.(*childQuery).Select(0xc014e079e0, {0x28782a0, 0xc01298b3e0})
        github.com/antchfx/xpath@v1.2.2/query.go:183 +0x62
github.com/antchfx/xpath.(*childQuery).Select(0xc014e07a10, {0x28782a0, 0xc01298b3e0})
        github.com/antchfx/xpath@v1.2.2/query.go:183 +0x62
github.com/antchfx/xpath.(*childQuery).Select(0xc014e07a40, {0x28782a0, 0xc01298b3e0})
        github.com/antchfx/xpath@v1.2.2/query.go:183 +0x62
github.com/antchfx/xpath.(*NodeIterator).MoveNext(0xc01298b3e0)
        github.com/antchfx/xpath@v1.2.2/xpath.go:86 +0x38
github.com/antchfx/htmlquery.QuerySelectorAll(0xc0004ead20, 0xc0132831c0)
        github.com/antchfx/htmlquery@v1.2.6/query.go:83 +0x125
github.com/antchfx/htmlquery.QueryAll(0x287cb20?, {0xc0047c6d40?, 0x138a885?})
        github.com/antchfx/htmlquery@v1.2.6/query.go:54 +0x52
github.com/projectdiscovery/nuclei/v2/pkg/operators/extractors.(*Extractor).ExtractHTML(0xc0047adb00, {0xc00fb73a00, 0x1af})
        github.com/projectdiscovery/nuclei/v2/pkg/operators/extractors/extract.go:79 +0x10d
github.com/projectdiscovery/nuclei/v2/pkg/operators/extractors.(*Extractor).ExtractXPath(0x60?, {0xc00fb73a00?, 0x1af?})
        github.com/projectdiscovery/nuclei/v2/pkg/operators/extractors/extract.go:67 +0x5d
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).Extract(0x58?, 0x1f21360?, 0xc0047adb00)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/operators.go:71 +0x115
github.com/projectdiscovery/nuclei/v2/pkg/operators.(*Operators).Execute(0xc004155a40, 0xc011bd25d0, 0xc005ed0a50, 0xc005ed0a38, 0x0)
        github.com/projectdiscovery/nuclei/v2/pkg/operators/operators.go:225 +0x1a2
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/helpers/eventcreator.CreateEventWithAdditionalOptions({0x2898e80?, 0xc004155a40}, 0xc011bd25d0, 0x4?, 0xc005ed0ef0)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/helpers/eventcreator/eventcreator.go:28 +0x1d9
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc004155a40, 0xc0150bea00, 0xc012f5d270, 0xc0150bea00?, 0x0, 0xc005ed1800, 0xd?)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:744 +0x29a5
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc004151b60, 0x28}, 0x0, 0xc014551e90)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:383 +0x8e5
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc004155a40, 0xc0150bea00, 0xc014551e90, 0xc014551ec0, 0xc014551f20)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:435 +0x36a
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc004663c00, 0xc0150be960)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer/executer.go:80 +0x39f
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0xf8ef270?, 0xc0?, 0xc0150be220)
        github.com/projectdiscovery/nuclei/v2/pkg/core/executors.go:130 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
        github.com/projectdiscovery/nuclei/v2/pkg/core/executors.go:107 +0x4f8

**Comment by ehsandeep** [comment] 2023-02-09 13:09
@reconnization duplicate of https://github.com/projectdiscovery/nuclei/issues/3253

**Closed by ehsandeep** 2023-02-09 13:09 UTC
Labels: Type: Bug
