### ISSUE TITLE
Unable to install nuclei in Docker image - invalid version: unknown revision

### ISSUE THREAD

**Issue by alex700** [projectdiscovery/nuclei#4146] opened 2023-09-12 22:50 UTC
### Current Behavior:
Create a `Dockerfile`:

```
FROM public.ecr.aws/lambda/provided:al2 AS build
ENV CGO_ENABLED=0
WORKDIR /app
RUN mkdir -p /opt/extensions
RUN yum -y install go
RUN go env -w GOPROXY=direct
COPY go.mod go.sum ./
COPY main.go .
RUN go mod download
RUN env GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o main main.go
RUN go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
```
Run build like this:
```
docker build --platform linux/arm64 -t $(IMAGE_NAME):latest .
```

### Expected Behavior:
Docker built successfully

### Actual Result
Build finishes with the error:

```
...
...
...
#0 183.7 get "gopkg.in/tomb.v1": found meta tag vcs.metaImport{Prefix:"gopkg.in/tomb.v1", VCS:"git", RepoRoot:"https://gopkg.in/tomb.v1"} at //gopkg.in/tomb.v1?go-get=1
#0 221.2 get "go.uber.org/atomic": found meta tag vcs.metaImport{Prefix:"go.uber.org/atomic", VCS:"git", RepoRoot:"https://github.com/uber-go/atomic"} at //go.uber.org/atomic?go-get=1
#0 256.3 go: github.com/projectdiscovery/goflags@v0.0.10-0.20220912115102-d9ea875a0a6a: invalid version: unknown revision d9ea875a0a6a
------
Dockerfile:11
--------------------
   9 |     RUN go mod download
  10 |     RUN env GOOS=linux GOARCH=arm64 go build -tags lambda.norpc -o main main.go
  11 | >>> RUN go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
  12 |     
  13 |     # FROM projectdiscovery/nuclei:latest as build-nuclei
--------------------
ERROR: failed to solve: process "/bin/sh -c go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei" did not complete successfully: exit code: 1
make: *** [build-arm64] Error 1
```

**Comment by MetzinAround** [comment] 2023-09-13 15:44
Not sure if it helps, but we have a blog on using nuclei in docker. https://blog.projectdiscovery.io/how-to-run-nuclei-other-projectdiscovery-tools-in-docker/

**Comment by alex700** [comment] 2023-09-14 00:17
Thank you, @MetzinAround. Unfortunately, it does not help me because I need to use another docker image: `public.ecr.aws/lambda/provided:al2`

The reason - I need to use the `nuclei` inside a Go-based AWS lambda function. For example:
```
func HandleRequest(ctx context.Context, event events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	cmd := exec.Command("/var/runtime/nuclei", "-u", "https://my-site.com", "-silent", "-json")
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	cmdErr := cmd.Run()

        outStr, errStr := stdout.String(), stderr.String()
	fmt.Printf("out:\n%s\nerr:\n%s\n", outStr, errStr)

        response := events.APIGatewayProxyResponse {
		StatusCode: 200,
		Body:       outStr,
	}

	return response, cmdErr
}
```

I use [arm64](https://docs.aws.amazon.com/lambda/latest/dg/go-image.html#go-image-al2) and need the compatible docker image. That's why I can't include `projectdiscovery/nuclei:latest` in my build and copy it to the target image. I tried to do the installation of `nuclei` to the target image to copy it after this to the target image.  
As a temporary workaround, I clone the repository and build Niclei from there. My docker might look more compact if I can set it up with `Go`.

**Comment by dogancanbakir** [comment] 2023-09-14 11:59
@alex700 ,
Changing `RUN go env -w GOPROXY=direct` with `RUN go env -w GOPROXY=https://proxy.golang.org` might solve your problem. Please keep us posted.

**Comment by alex700** [comment] 2023-09-15 04:20
It works. Thank you! 
I caught a strange behavior. When I try to install `nuclei` in `public.ecr.aws/lambda/provided:al2` image, it copies the source files instead. But when I do it in `golang:1.20`, it installs the binary file properly. 

The solution (`arm64`) looks like this:

```
# Build lambda function
FROM public.ecr.aws/lambda/provided:al2 AS build-lambda
ENV GOARCH=arm64
ENV GOOS=linux
ENV CGO_ENABLED=0
WORKDIR /app
RUN mkdir -p /opt/extensions
RUN yum -y install go
RUN go env -w GOPROXY=https://proxy.golang.org
COPY go.mod go.sum ./
COPY main.go .
RUN go mod download
RUN go build -tags lambda.norpc -o main main.go

# Install nuclei
FROM golang:1.20 AS build-nuclei
ENV GOARCH=arm64
ENV GOOS=linux
ENV CGO_ENABLED=0
# Install nuclei
RUN go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest

# Target Image
# ==================================================================================================
FROM public.ecr.aws/lambda/provided:al2
COPY --from=build-nuclei /go/bin/nuclei ${LAMBDA_RUNTIME_DIR}/nuclei
COPY --from=build-lambda /app/main ./main
ENTRYPOINT [ "./main" ]

```

**Comment by dogancanbakir** [comment] 2023-09-15 08:24
This issue may be caused by the behavior introduced in [Go 1.20](https://go.dev/doc/go1.20), or by the way the [environment](https://github.com/docker-library/golang) is configured. I am closing this as resolved, but please feel free to reopen if you have any further questions.

**Closed by dogancanbakir** 2023-09-15 08:24 UTC
Labels: Type: Bug
