### ISSUE TITLE
Ouput results shows only found results

### ISSUE THREAD

**Issue by Zeokat** [projectdiscovery/nuclei#67] opened 2020-04-29 19:18 UTC
There is a bug showing output results, and Nuclei only shows found results, even when we don't use `-silent`.

I know that the switch `-silent` is designed to show only found results, but seems that this switch is always active because the output never shows full results.

It was reported at https://github.com/projectdiscovery/nuclei/issues/65#issuecomment-621405072 and seems that the bug is present for all.

Hope you can fix this.

**Comment by bauthard** [comment] 2020-04-29 20:13
Hi @Zeokat, 

Thanks for creating an issue, it's always good to create each issue for each feature, and I agree with the point that we should add more details in the verbose mode, and I can confirm it's not a bug, Nuclei only prints out the valid result on the default run,  `-silent` is used to disable the banner only. 

We will add more detail with `-v`  flag in coming updates to list all valid requests we sent using nuclei and we already have an issue created for this at https://github.com/projectdiscovery/nuclei/issues/22, so this is duplicate.

**Comment by bauthard** [comment] 2020-04-29 20:13
@amiralkizaru^

**Comment by bauthard** [comment] 2020-04-29 20:21
Closing this as this turned out to be a duplicate issue.

**Closed by bauthard** 2020-04-29 20:21 UTC

**Comment by amiralkizaru** [comment] 2020-07-18 11:48
@bauthard @Zeokat 
This is fixed in the latest version now 
Thank's
