### ISSUE TITLE
Deleting the templates directory and doing a template update returns incorrect response

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#1324] opened 2021-12-03 12:34 UTC
Steps to reproduce:
* `nuclei -update-directory /tmp/nuclei-templates -update-templates`
* `rm -rf /tmp/nuclei-templates`
* `nuclei -update-directory /tmp/nuclei-templates -update-templates`

Expected: Nuclei realizes that the templates are not present and does an update
Actual: "Your nuclei-templates are up to date: vX.Y.Z"

![image](https://user-images.githubusercontent.com/13679401/142046995-5bf38df3-44c7-494d-96ec-787f4e2c223e.png)

**Comment by gaby** [comment] 2021-12-08 05:32
I'm running into the same issue, since 2.5.2 I lost the ability to update templates.

We build our own image based on the official one and call "update-templates" and it now fails all the time. 

We get even more errors if disabling auto-updates of templates.

There is no reason why a Docker container should be changing it's initial code, by auto-updating.

**Comment by ehsandeep** [comment] 2021-12-08 11:48
@gaby 

> We get even more errors if disabling auto-updates of templates.

Can you share more details about this?

**Comment by ThreeGold127** [comment] 2021-12-12 14:33
same too

**Comment by ehsandeep** [comment] 2021-12-13 10:52
This is a duplicate of https://github.com/projectdiscovery/nuclei/issues/1196 and being handled in https://github.com/projectdiscovery/nuclei/pull/1212

**Closed by ehsandeep** 2021-12-13 10:52 UTC
Labels: Priority: Medium, Type: Bug
