### ISSUE TITLE
Issue with template loading with same name

### ISSUE THREAD

**Issue by NagliNagli** [projectdiscovery/nuclei#2465] opened 2022-08-21 11:37 UTC
### Nuclei version:
latest

### Current Behavior:

Lets say I have a template: `nagli.yaml` on my current directory.

I also have a template called: `nagli.yaml` on `~/Desktop/my-nuclei-templates/nagli.yaml`

If I opt to run: `echo "https://test.com" | nuclei -t ~/Desktop/my-nuclei-templates/nagli.yaml`

it will run the `nagli.yaml` which is the current directory, and not the one I specified

### Expected Behavior:

The expected behavior would be to run the template I specified.

----

Related issue - https://github.com/projectdiscovery/nuclei/issues/1332

**Comment by parrasajad** [comment] 2022-10-18 12:36
@NagliNagli  not able to reproduce the bug.

**Comment by Mzack9999** [comment] 2022-11-29 15:43
Closing the issue as the problem was not reproducible - Please feel free to comment if you still have the problem. We will be happy to have a second look. Thanks!

**Closed by Mzack9999** 2022-11-29 15:43 UTC
Labels: Priority: Medium, Type: Bug, Investigation
