### ISSUE TITLE
Could not initialize protocols

### ISSUE THREAD

**Issue by FuckAllWorld** [projectdiscovery/nuclei#2583] opened 2022-09-10 01:01 UTC
Could not initialize protocols: could not create dialer: mkdir /tmp/hm4232307751: no space left on device

create a lot of files on tmp

**Comment by jimen0** [comment] 2022-09-12 08:28
Same as #2586, in case you want to close it as a dupe @forgedhallpass @ehsandeep

**Comment by Mzack9999** [comment] 2022-11-23 14:43
The issue is tracked at https://github.com/projectdiscovery/hmap/issues/54 - we will try to reduce the db fragmentation, but unfortunately, I think there isn't a lot we can do with full disk

**Closed** 2022-11-23 14:43 UTC
Labels: Type: Bug
