### ISSUE TITLE
extractors regex internal get extra data []

### ISSUE THREAD

**Issue by passwa11** [projectdiscovery/nuclei#4617] opened 2024-01-11 04:33 UTC
### Nuclei version:

v3.1.5
### Current Behavior:

flow: http(1)&&http(2)
extractors in http(1)
timestrp used in http(2)
```
extractors:
      - type: regex # type of the extractor
        part: body  # part of the response (header,body,all)
        name: timestrp
        internal: true
        group: 1
        regex:
          - '\d{6}\\(\d+)\.'
```
strings : `\somgstr\202401\2024011010161234.jpg` but the nuclei debug info 
```
[2024011010161234]
```
get extra data [ ] !! if not use  flow: http(1)&&http(2) the extractors work well.
### Expected Behavior:

only 2024011112143362

**Comment by ehsandeep** [comment] 2024-01-11 11:49
@passwa11 this is duplicate of https://github.com/projectdiscovery/nuclei/issues/4547, follow https://github.com/projectdiscovery/nuclei/issues/4547 for update / fix.

**Closed by ehsandeep** 2024-01-11 11:49 UTC
Labels: Type: Bug

**Comment by passwa11** [comment] 2024-01-11 12:51
got it!
