### ISSUE TITLE
The program created too many directories in the /tmp directory

### ISSUE THREAD

**Issue by kw0ngr** [projectdiscovery/nuclei#2586] opened 2022-09-11 07:04 UTC
Error:
Could not initialize protocols: could not create dialer: mkdir /tmp/hm4232307751: no space left on device

At the end of the program scan, the temporary files should be cleaned up.

**Comment by ehsandeep** [comment] 2022-09-11 08:39
@kw0ngr what version of nuclei you running?

**Comment by kw0ngr** [comment] 2022-09-11 11:53
@ehsandeep v2.7.7

**Comment by forgedhallpass** [comment] 2022-09-12 13:51
Duplicate of #2583

**Closed** 2022-09-12 13:51 UTC
Labels: Type: Bug
