### ISSUE TITLE
Doesn't build on i386 (untyped int constant)

### ISSUE THREAD

**Issue by nunotexbsd** [projectdiscovery/nuclei#2801] opened 2022-11-03 21:51 UTC
### Nuclei version:

2.7.8 (go 1.19.3)

### Current Behavior:

Doesn't build on i386 arch:
```
# github.com/projectdiscovery/nuclei/v2/pkg/utils/ratelimit
pkg/utils/ratelimit/ratelimit.go:59:13: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in struct literal (overflows)
pkg/utils/ratelimit/ratelimit.go:60:13: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in struct literal (overflows)
(...)
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/protocolinit
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/variables
github.com/projectdiscovery/nuclei/v2/pkg/protocols/headless/engine
*** Error code 2

```
### Expected Behavior:

2.7.7 builds fine, I was expecting it build too on 2.7.8

**Comment by ehsandeep** [comment] 2022-11-04 09:13
@nunotexbsd thanks for flagging, looks duplicate of https://github.com/projectdiscovery/nuclei/issues/2747 and will be fixed as part of https://github.com/projectdiscovery/ratelimit/issues/4

**Closed by ehsandeep** 2022-11-04 09:13 UTC
Labels: Type: Bug
