### ISSUE TITLE
Invalid Memory Address Or Nil Pointer Dereference - Nuclei 2.5.1

### ISSUE THREAD

**Issue by HolyBugx** [projectdiscovery/nuclei#1029] opened 2021-09-16 08:58 UTC
**Describe the bug**

Hello PD,

While running the latest version of nuclei on a large number of subdomains I faced an error regarding the GO pointers.

```
panic: runtime error: invalid memory address or nil pointer dereference
```

**Nuclei version**
2.5.1

**Screenshot of the error or bug**
<img width="974" alt="Screen Shot 2021-09-16 at 13 25 55" src="https://user-images.githubusercontent.com/71842138/133582700-8fa0b3c3-e7a9-4817-a381-8d36b208c63f.png">

**Comment by ehsandeep** [comment] 2021-09-16 09:08
Hi @HolyBugx, this is a duplicate of https://github.com/projectdiscovery/nuclei/issues/998 and fixed by https://github.com/projectdiscovery/fastdialer/pull/24, new release will be created asap.

**Closed by ehsandeep** 2021-09-16 09:08 UTC
