### ISSUE TITLE
How do I set the template to use the helpers/wordlists file of the directory I defined

### ISSUE THREAD

**Issue by boluoha** [projectdiscovery/nuclei#2770] opened 2022-10-28 08:55 UTC
I have tried to copy a template to another directory, and then set USERPROFILE and HOMEPATH as the parameters of the copied directory, but it seems to be useless?
I would like to know how to set the parameters of the helpers/wordlists file, can you help me?

**Comment by forgedhallpass** [comment] 2022-11-02 00:19
Duplicate of https://github.com/projectdiscovery/nuclei/discussions/2769

**Closed by forgedhallpass** 2022-11-02 00:19 UTC
Labels: Type: Enhancement
