### ISSUE TITLE
Excessive leftover files in /tmp after running Nuclei tool multiple times

### ISSUE THREAD

**Issue by martiGIT** [projectdiscovery/nuclei#3693] opened 2023-05-16 10:44 UTC
### Nuclei version: v2.9.4
Same problem happens with httpx current version (not sure if I should create separate ticket)

### Current Behavior:
Hi!
I'm using Nuclei tool on a Linux-based system, and I've observed an issue where, after running Nuclei over 100,000 times, I've been left with a significant number of leftover files in the /tmp directory. These files are filling up the inode on my Linux system, creating a potential problem with storage space and system performance.
Each leftover directory contains the following files:
```
-rw-r--r-- 1 testing testing     52 May 16 08:20 000001.log
-rw-r--r-- 1 testing testing     16 May 16 08:20 CURRENT
-rw-r--r-- 1 testing testing      0 May 16 08:20 LOCK
-rw-r--r-- 1 testing testing    358 May 16 08:20 LOG
-rw-r--r-- 1 testing testing     54 May 16 08:20 MANIFEST-000000
```

### Expected Behavior:
Ideally, I would like to propose two possible solutions to this problem:

- Do not create these files: If these files are not essential to the functionality of the nuclei, it would be best not to create them in the first place.
- Cleanup after running: If these files are necessary for the tool to function correctly, then nuclei/httpx should be responsible for cleaning up these files once it has finished running.

### Steps To Reproduce:

Run nuclei that fails (for example not existing domains)

### Anything else:
The only workaround I've found for this issue thus far is to delete these files via a cron job, but this is not an ideal solution, as it requires manual intervention and additional system resources.

I hope this report provides enough information to address this issue. If you need further details, please let me know.

Thank you for your attention to this matter.

Best Regards,
Marcin

**Comment by ehsandeep** [comment] 2023-05-16 10:55
Thank you @martiGIT for reporting this! those files are expected and created as per the use of [hmap](https://github.com/projectdiscovery/hmap) library for input processing and should be cleaned up automatically, we will investigate and update it back.

**Comment by martiGIT** [comment] 2023-05-26 14:51
Hi @Mzack9999 , thanks for your answer, in my case I run nuclei and httpx in a docker container, but the same problem happens with standalone binary. Here you can find a result of standalone command

```
m@learning:~$ ls -al /tmp/nuclei*
ls: cannot access '/tmp/nuclei*': No such file or directory
m@learning:~$ ls -al /tmp/httpx*
ls: cannot access '/tmp/httpx*': No such file or directory
```
but even without running it in a container, the following command leaves undeleted files behind
```
./httpx -td -nc -follow-redirects -status-code -tech-detect -u https://example.com/
[INF] Current httpx version v1.3.1 (latest)
https://example.com/ [200] [Amazon ECS,Amazon Web Services,Azure,Azure CDN,Docker]
```
```
ls -ald /tmp/httpx*
drwx------ 2 m m 4096 May 26 10:39 /tmp/httpx1041100930
drwx------ 2 m m 4096 May 26 10:39 /tmp/httpx2020575735
```
running it twice (command above) left even more:
```
m@learning:~$ ls -ald /tmp/httpx*
drwx------ 2 m m 4096 May 26 10:39 /tmp/httpx1041100930
drwx------ 2 m m 4096 May 26 10:42 /tmp/httpx180370152
drwx------ 2 m m 4096 May 26 10:39 /tmp/httpx2020575735
drwx------ 2 m m 4096 May 26 10:42 /tmp/httpx384158440
```

same situation with nuclei, I use command like below:
```
./nuclei -nc --tags top-100 -u example.pl
[WRN] Found 24 template[s] loaded with deprecated paths, update before v2.9.5 for continued support.
[INF] Current nuclei version: v2.9.4 (latest)
[INF] Current nuclei-templates version: v9.5.0 (latest)
[INF] New templates added in latest release: 62
[INF] Templates loaded for current scan: 100
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
```
result after the first pass:
```
ls -ald /tmp/nuclei*
drwx------ 2 m m 4096 May 26 10:43 /tmp/nuclei2007766952
drwx------ 2 m m 4096 May 26 10:43 /tmp/nuclei3907341496
```
2nd:
```
ls -ald /tmp/nuclei*
drwx------ 2 m m 4096 May 26 10:43 /tmp/nuclei2007766952
drwx------ 2 m m 4096 May 26 10:43 /tmp/nuclei3907341496
drwx------ 2 m m 4096 May 26 10:46 /tmp/nuclei4230128635
drwx------ 2 m m 4096 May 26 10:46 /tmp/nuclei975175988
```
So as you can see - no crash happens here. So I assume it should be deleted immediately. Thanks in advance for help

**Comment by Mzack9999** [comment] 2023-05-29 11:04
@martiGIT I suspect this is an indirect effect of https://github.com/projectdiscovery/httpx/issues/1086 and probably fixed in `dev` as I'm unable to reproduce it:

```console
$ docker run -it ubuntu:23.10 bash
root@8b79fbcbd508:/# apt install golang build-essential git curl wget
root@8b79fbcbd508:/# go install -v github.com/projectdiscovery/httpx/cmd/httpx@dev
root@8b79fbcbd508:~/go/bin# ls -la /tmp/
total 8
drwxrwxrwt 1 root root 4096 May 29 10:49 .
drwxr-xr-x 1 root root 4096 May 29 10:45 ..
root@8b79fbcbd508:~/go/bin# ./httpx -td -nc -follow-redirects -status-code -tech-detect -u https://example.com/

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current httpx version v1.3.1 (latest)
https://example.com/ [200] [Amazon ECS,Amazon Web Services,Azure,Azure CDN,Docker]
root@8b79fbcbd508:~/go/bin# ls -la /tmp/
total 8
drwxrwxrwt 1 root root 4096 May 29 10:58 .
drwxr-xr-x 1 root root 4096 May 29 10:45 ..
root@8b79fbcbd508:~/go/bin#
```

If confirmed, the new release should fix the problem indirectly. Thanks!

**Comment by Mzack9999** [comment] 2023-06-28 09:29
Not anymore reproducible, will be reopened in case the problem appears again - Closing as completed

**Closed by Mzack9999** 2023-06-28 09:29 UTC
Labels: Status: Completed, Type: Bug, Investigation
