### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference (in v2.9.3-dev)

### ISSUE THREAD

**Issue by marrco** [projectdiscovery/nuclei#3619] opened 2023-04-27 14:06 UTC
### Nuclei version:

 v2.9.3-dev (development)  (downloaded 0427)

### Current Behavior:

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1540f5b]

goroutine 152321 [running]:
github.com/projectdiscovery/tlsx/pkg/tlsx/ztls.(*Client).ConnectWithOptions(0xc00ba4ebb8, {0xc00cb0d290, 0x10}, {0xc00cb0d290, 0x10}, {0xc00cb0d2a1, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.7/pkg/tlsx/ztls/ztls.go:153 +0x5bb
github.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0xc00ba4ebd0, {0xc00cb0d290, 0x10}, {0xc00cb0d290, 0x10}, {0xc00cb0d2a1, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.7/pkg/tlsx/auto/auto.go:49 +0x178
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0xc00ba4eb88, {0xc00cb0d290, 0x10}, {0xc00cb0d290, 0x10}, {0xc00cb0d2a1, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.7/pkg/tlsx/tlsx.go:74 +0x243
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).Connect(...)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.7/pkg/tlsx/tlsx.go:60
github.com/projectdiscovery/nuclei/v2/pkg/protocols/ssl.(*Request).ExecuteWithResults(0xc002b347e0, 0xc00836efa0, 0x7f9cd869f908?, 0x7f9d1aa9e5b8?, 0xc008b06750)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230426184535-78f1ade6c698/pkg/protocols/ssl/ssl.go:218 +0x62d
github.com/projectdiscovery/nuclei/v2/pkg/templates.(*ClusterExecuter).Execute(0xc005fced00, 0xc00836ef20)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230426184535-78f1ade6c698/pkg/templates/cluster.go:245 +0x22d
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x6203ca?, 0x0?, 0xc00836e720)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230426184535-78f1ade6c698/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230426184535-78f1ade6c698/pkg/core/executors.go:105 +0x4f8
```

### Expected Behavior:

no crash 

### Steps To Reproduce:

 sudo go/bin/nuclei -no-interactsh -rl 50 -list listoftargets.txt

### Anything else:

this is NOT the same error I reported a few hours ago (https://github.com/projectdiscovery/nuclei/issues/3617) that was related with interactsh. This is a new issue still not fixed in v2.9.3-dev (development)

**Comment by coj337** [comment] 2023-04-27 15:59
+1 to this, I'm running into some documented issues on the current version and what looks like this issue in dev.

**Comment by MetzinAround** [comment] 2023-04-27 18:44
Hi all! Thanks for the issue. We have another issue with this and I believe it's been fixed in the dev branch. 

https://github.com/projectdiscovery/nuclei/issues/3603

**Comment by ehsandeep** [comment] 2023-04-27 22:50
@marrco @coj337 this crash should be fixed with https://github.com/projectdiscovery/nuclei/pull/3620 or let me know if you have an example to share.

**Comment by marrco** [comment] 2023-04-28 08:01
updated to the newest v2.9.3-dev and rerun the same test. Same error.

maybe i did a mistake somewhere
> sudo rm /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.* -rf
(and verified)
go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@tlsx-dep-update
now i get tlsx@v1.0.8 but still:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1540f1b]

goroutine 30425 [running]:
github.com/projectdiscovery/tlsx/pkg/tlsx/ztls.(*Client).ConnectWithOptions(0xc0075b96c8, {0xc00451dbf0, 0x10}, {0xc00451dbf0, 0x10}, {0xc00451dc01, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/ztls/ztls.go:158 +0x5bb
github.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0xc0075b96e0, {0xc00451dbf0, 0x10}, {0xc00451dbf0, 0x10}, {0xc00451dc01, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/auto/auto.go:49 +0x178
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0xc0075b9698, {0xc00451dbf0, 0x10}, {0xc00451dbf0, 0x10}, {0xc00451dc01, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/tlsx.go:74 +0x243
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).Connect(...)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/tlsx.go:60
github.com/projectdiscovery/nuclei/v2/pkg/protocols/ssl.(*Request).ExecuteWithResults(0xc00013ca80, 0xc003965e20, 0x2?, 0xfe?, 0xc00547d2c0)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/protocols/ssl/ssl.go:218 +0x62d
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc0075a9b20, 0xc003965ac0)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/protocols/common/executer/executer.go:81 +0x383
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x760ec6?, 0x0?, 0xc0068a71e0)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/core/executors.go:105 +0x4f8`

**Comment by marrco** [comment] 2023-04-28 08:11
I did a few tests, same error, so i tried to start clean:
`~$ sudo rm /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nucl* -rf
~$ sudo rm /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tls* -rf
~$ go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@dev
~$ go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@6321dd8a8787c7506a682f96e00c02b3c0460d61
~$  sudo go/bin/nuclei -no-interactsh -rl 50 -list listoftargets.txt
`

`
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.3-dev

                projectdiscovery.io

[INF] Current nuclei version: v2.9.3-dev (development)
[INF] Current nuclei-templates version: v9.4.3 (latest)
[INF] New templates added in latest release: 55
[INF] Templates loaded for current scan: 5901
[INF] Targets loaded for current scan: 62
[INF] Running httpx on input host
[INF] Found 5 URL from httpx
[INF] Templates clustered: 1055 (Reduced 60450 Requests)
[tech-detect:ms-httpapi] [http] [info] https://ccc.mydomain.com:5986
[tech-detect:ms-httpapi] [http] [info] http://ccc.mydomain.com:5985
[tech-detect:ms-httpapi] [http] [info] http://aaa.mydomain.com:5985
[tech-detect:ms-httpapi] [http] [info] http://bbb.mydomain.com:5985
[tech-detect:ms-httpapi] [http] [info] http://aaa.mydomain.com:5985
[tech-detect:ms-httpapi] [http] [info] https://ccc.mydomain.com:5986
[tech-detect:ms-httpapi] [http] [info] http://bbb.mydomain.com:5985
[samba-detect] [tcp] [info] aaa.mydomain.com:445
[samba-detect] [tcp] [info] bbb.mydomain.com:445
[samba-detect] [tcp] [info] ccc.mydomain.com:445
[self-signed-ssl] [ssl] [low] aaa.mydomain.com:3389
[mismatched-ssl-certificate] [ssl] [low] ccc.mydomain.com:5986 [CN: ds-csdc01.cloudapp.net]
[revoked-ssl-certificate] [ssl] [low] ccc.mydomain.com:5986
[self-signed-ssl] [ssl] [low] ccc.mydomain.com:5986
[expired-ssl] [ssl] [low] ccc.mydomain.com:5986 [2023-04-16 12:00:00 +0000 UTC]
[self-signed-ssl] [ssl] [low] bbb.mydomain.com:3389
[mismatched-ssl-certificate] [ssl] [low] ccc.mydomain.com:5986 [CN: ds-csdc01.cloudapp.net]
[revoked-ssl-certificate] [ssl] [low] ccc.mydomain.com:5986
[self-signed-ssl] [ssl] [low] ccc.mydomain.com:5986
[expired-ssl] [ssl] [low] ccc.mydomain.com:5986 [2023-04-16 12:00:00 +0000 UTC]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1540f1b]

goroutine 83508 [running]:
github.com/projectdiscovery/tlsx/pkg/tlsx/ztls.(*Client).ConnectWithOptions(0xc0031efb78, {0xc00d0fc240, 0x10}, {0xc00d0fc240, 0x10}, {0xc00d0fc251, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/ztls/ztls.go:158 +0x5bb
github.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0xc0031efbc0, {0xc00d0fc240, 0x10}, {0xc00d0fc240, 0x10}, {0xc00d0fc251, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/auto/auto.go:49 +0x178
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0xc0031efa70, {0xc00d0fc240, 0x10}, {0xc00d0fc240, 0x10}, {0xc00d0fc251, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/tlsx.go:74 +0x243
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).Connect(...)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/tlsx.go:60
github.com/projectdiscovery/nuclei/v2/pkg/protocols/ssl.(*Request).ExecuteWithResults(0xc000042c40, 0xc00d288440, 0x7f7319f4d590?, 0x7f734bb93108?, 0xc00d2ce258)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/protocols/ssl/ssl.go:218 +0x62d
github.com/projectdiscovery/nuclei/v2/pkg/templates.(*ClusterExecuter).Execute(0xc00540e4c0, 0xc00d2883e0)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/templates/cluster.go:245 +0x22d
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x760f26?, 0x0?, 0xc00bdedfe0)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/core/executors.go:105 +0x4f8
myhomedir@Prometeo:~$`

**Comment by Teicu** [comment] 2023-04-28 11:04
same here
 
<img width="1468" alt="Screenshot 2023-04-28 at 12 04 12" src="https://user-images.githubusercontent.com/1572822/235131683-6f636f98-7bf7-4e73-bc52-88d45f26c51b.png">

**Comment by Teicu** [comment] 2023-04-28 11:16
btw, what means this? I have already done the update twice and it shows me that it is outdated? I use MacBook Apple M2 Max

> [INF] nuclei-templates are not installed, installing...
> [INF] Successfully installed nuclei-templates at /var/root/nuclei-templates
> [INF] Your current nuclei-templates v9.4.3 are **outdated**. Latest is v9.4.3
> [INF] **Successfully updated** nuclei-templates (v9.4.3) to /var/root/nuclei-templates. GoodLuck!
> [INF] Current nuclei version: v2.9.2 (**outdated**)
> [INF] Current nuclei-templates version: v9.4.3 (**outdated**)

**Comment by ehsandeep** [comment] 2023-04-28 11:44
@Teicu please open separate [discussion](https://github.com/projectdiscovery/nuclei/discussions/categories/q-a) for a separate discussion.

@marrco we attempted to fix the issue here - https://github.com/projectdiscovery/tlsx/pull/248, since we are not able to reproduce this on our side, we need a host that we can use to reproduce and confirm the fix.

is it possible for you to share an example host that can be used to confirm the issue and fix on discord? my username is - `pdteam#5974`

**Comment by marrco** [comment] 2023-04-28 16:00
I singled out the PORT on a specific internal ip (using fqdn or IP makes no difference) that causes nuclei to crash.

sudo go/bin/nuclei -no-interactsh -rl 50 -u 172.30.30.30:5666

```
[INF] Templates clustered: 1055 (Reduced 975 Requests)
[rdp-detect:win2012R2] [tcp] [info] 172.30.30.30:3389
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1540f1b]

goroutine 5446 [running]:
github.com/projectdiscovery/tlsx/pkg/tlsx/ztls.(*Client).ConnectWithOptions(0xc0023dbec0, {0xc00a800d98, 0xd}, {0xc00a800d98, 0xd}, {0xc00a800da6, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/ztls/ztls.go:158 +0x5bb
github.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0xc0023dbef0, {0xc00a800d98, 0xd}, {0xc00a800d98, 0xd}, {0xc00a800da6, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/auto/auto.go:49 +0x178
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0xc0023dbe90, {0xc00a800d98, 0xd}, {0xc00a800d98, 0xd}, {0xc00a800da6, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/tlsx.go:74 +0x243
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).Connect(...)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/tlsx.go:60
github.com/projectdiscovery/nuclei/v2/pkg/protocols/ssl.(*Request).ExecuteWithResults(0xc0001528c0, 0xc007397f40, 0xc00ad60fc0?, 0xc00ad60ff0?, 0xc00ad61020)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/protocols/ssl/ssl.go:218 +0x62d
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc002354a80, 0xc007397e60)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/protocols/common/executer/executer.go:81 +0x383
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x160122a?, 0x0?, 0xc007397de0)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/core/executors.go:105 +0x4f8
```

sudo go/bin/nuclei -no-interactsh -rl 50 -u 172.30.30.30:5666 -v
(...)

```
[WRN] [nameserver-fingerprint] Could not execute request for 172.30.30.30:5666: could not build request: cannot use IP address as DNS input
[VER] Sent TCP request to 172.30.30.30:5666
[WRN] Could not make network request for 172.30.30.30:21: could not connect to server request: could not connect to any address found for host
[WRN] [cluster-3da970b235e958896fbc481c57b6af660cfbb0399f76136f3c586b9892ff0242] Could not execute step: [urlutil:RUNTIME] failed to parse url got empty input
[VER] Sent TCP request to 172.30.30.30:5666
[VER] Sent TCP request to 172.30.30.30:5666
[VER] Sent TCP request to 172.30.30.30:5666
[WRN] Could not make network request for 172.30.30.30:9092: could not connect to server request: could not connect to any address found for host
[VER] Sent TCP request to 172.30.30.30:5666
[VER] Sent TCP request to 172.30.30.30:445
[WRN] [cluster-b7cf089769274ce961b83dfea4aa1763d25bdcdc56f00001e0f38ea7e1520c79] Could not execute step: [urlutil:RUNTIME] failed to parse url got empty input
[VER] Sent TCP request to 172.30.30.30:5666
[WRN] Could not make network request for 172.30.30.30:5666: could not read from server: read tcp 172.22.219.122:38118->172.30.30.30:5666: read: connection reset by peer
[WRN] Could not make network request for 172.30.30.30:5666: could not write request to server: write tcp 172.22.219.122:38150->172.30.30.30:5666: write: broken pipe
[WRN] Could not make network request for 172.30.30.30:5666: could not write request to server: write tcp 172.22.219.122:38170->172.30.30.30:5666: write: broken pipe
[VER] Sent TCP request to 172.30.30.30:5666
[WRN] Could not make network request for 172.30.30.30:11300: could not connect to server request: could not connect to any address found for host
[VER] Sent TCP request to 172.30.30.30:5666
[VER] Sent TCP request to 172.30.30.30:5666
[VER] Sent TCP request to 172.30.30.30:139
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1540f1b]

goroutine 5215 [running]:
github.com/projectdiscovery/tlsx/pkg/tlsx/ztls.(*Client).ConnectWithOptions(0xc001fbdd40, {0xc00bc4a978, 0xd}, {0xc00bc4a978, 0xd}, {0xc00bc4a986, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/ztls/ztls.go:158 +0x5bb
github.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0xc001fbdd58, {0xc00bc4a978, 0xd}, {0xc00bc4a978, 0xd}, {0xc00bc4a986, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/auto/auto.go:49 +0x178
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0xc001fbdd10, {0xc00bc4a978, 0xd}, {0xc00bc4a978, 0xd}, {0xc00bc4a986, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/tlsx.go:74 +0x243
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).Connect(...)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/tlsx.go:60
github.com/projectdiscovery/nuclei/v2/pkg/protocols/ssl.(*Request).ExecuteWithResults(0xc0008e08c0, 0xc00a5bcfe0, 0xc0076680f0?, 0xc007668120?, 0xc007668150)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/protocols/ssl/ssl.go:218 +0x62d
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc001fd3840, 0xc00a5bcf80)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/protocols/common/executer/executer.go:81 +0x383
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x160122a?, 0x0?, 0xc00a5bcee0)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/core/executors.go:105 +0x4f8
```

nmap 172.30.30.30 -Pn  -p 5666
PORT     STATE SERVICE
5666/tcp open  nrpe

**Comment by tarunKoyalwar** [comment] 2023-04-28 16:04
@marrco , the fix is not merged in nuclei there is a potential fix available in tlsx . so the error still exists . can you try to connect to this ip using below tlsx 
```
go install -v github.com/projectdiscovery/tlsx/cmd/tlsx@e23511a
```
also can you confirm there is a panic with above tlsx ^ if so can you share panic output

**Comment by marrco** [comment] 2023-04-29 18:31
@tarunKoyalwar I'll check and report next Tuesday. I have zero access to that network now.

**Comment by marrco** [comment] 2023-05-02 06:55
@tarunKoyalwar the issue is still present:

go install -v github.com/projectdiscovery/tlsx/cmd/tlsx@e23511a
sudo go/bin/nuclei -no-interactsh -rl 50 -u 172.30.30.30:5666




```
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.3-dev

                projectdiscovery.io

[INF] Current nuclei version: v2.9.3-dev (development)
[INF] Current nuclei-templates version: v9.4.3 (latest)
[INF] New templates added in latest release: 55
[INF] Templates loaded for current scan: 5901
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 0 URL from httpx
[INF] Templates clustered: 1051 (Reduced 973 Requests)
[rdp-detect:win2012R2] [tcp] [info] 172.30.30.30:3389
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1540f1b]

goroutine 10223 [running]:
github.com/projectdiscovery/tlsx/pkg/tlsx/ztls.(*Client).ConnectWithOptions(0xc00709f710, {0xc009341578, 0xd}, {0xc009341578, 0xd}, {0xc009341586, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/ztls/ztls.go:158 +0x5bb
github.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0xc00709f728, {0xc009341578, 0xd}, {0xc009341578, 0xd}, {0xc009341586, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/auto/auto.go:49 +0x178
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0xc00709f6e0, {0xc009341578, 0xd}, {0xc009341578, 0xd}, {0xc009341586, 0x4}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/tlsx.go:74 +0x243
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).Connect(...)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.8/pkg/tlsx/tlsx.go:60
github.com/projectdiscovery/nuclei/v2/pkg/protocols/ssl.(*Request).ExecuteWithResults(0xc000042fc0, 0xc009d69840, 0xc009d760c0?, 0xc009d760f0?, 0xc009d76120)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/protocols/ssl/ssl.go:218 +0x62d
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc007100300, 0xc009d697e0)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/protocols/common/executer/executer.go:81 +0x383
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x160122a?, 0x0?, 0xc009d69780)
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
        /home/myhomedir/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230427224703-6321dd8a8787/pkg/core/executors.go:105 +0x4f8
myhomedir@Prometeo:~$
```

**Comment by tarunKoyalwar** [comment] 2023-05-02 07:48
@marrco , the command you ran installed tlsx . Can you run command 
'''Console
tlsx -u 172.30.30.30:5666
'''
Thanks

**Comment by marrco** [comment] 2023-05-02 07:53
> @marrco , the command you ran installed tlsx . Can you run command
> 
> ```
> tlsx -u 172.30.30.30:5666 -v
> ```
> 
> Thanks

tlsx -u 172.30.30.30:5666 -v 

```
  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  <
   |_| |____|___/_/\_\  v1.0.8

                projectdiscovery.io

[INF] Current tlsx version v1.0.8 (latest)
[INF] Processing input 172.30.30.30:5666
[WRN] Could not write output 172.30.30.30:5666: [:RUNTIME] could not format output <- [:RUNTIME] empty leaf certificate
[INF] Connections made using crypto/tls: 0, zcrypto/tls: 
```1, openssl: 0

**Comment by tarunKoyalwar** [comment] 2023-05-02 07:56
Thanks looks like the issue is fixed in patched version of tlsx we will merge this patch in nuclei . and this should be resolved in next bug fix release 
cc: @ehsandeep

**Comment by knc331** [comment] 2023-05-03 11:39
I'm also facing the similar error with interactsh on v2.9.2 (latest)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe758e6]

goroutine 1077 [running]:
github.com/projectdiscovery/interactsh/pkg/client.(*Client).URL(0x0?)
        github.com/projectdiscovery/interactsh@v1.1.1-0.20230417162754-2cd861b12467/pkg/client/client.go:569 +0x26
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/interactsh.(*Client).URL(0xc000740000?)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/interactsh/interactsh.go:209 +0x8e
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/interactsh.(*Client).NewURLWithData(0xc000740000, {0xc0037fb5a0, 0x12})
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/interactsh/interactsh.go:251 +0x2c
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/interactsh.(*Client).ReplaceWithMarker(0xc00a058640?, {0xc0037fb500, 0xd2}, 0xc004ecf8c0?, {0x37d08b8, 0x0, 0x0})
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/interactsh/interactsh.go:238 +0x153
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/interactsh.(*Client).Replace(...)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/interactsh/interactsh.go:232
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*requestGenerator).Make(0xc00a986280, {0x28886c8, 0xc005db2c60}, 0xc0075d37e0, {0xc0037fb500?, 0xd2?}, 0xc006e57d10, 0xc006e57b30)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/build_request.go:77 +0xcb
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc0037fb500, 0xd2}, 0x1?, 0x30?)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:357 +0x167
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc002b781c0, 0xc0075d37e0, 0xc006e57b30, 0xc006e57bf0, 0xc006e57cb0)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:438 +0x36a
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc0021652a0, 0xc0075d3700)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer/executer.go:81 +0x397
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x15cf64a?, 0x0?, 0xc0075d3660)
        github.com/projectdiscovery/nuclei/v2/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
        github.com/projectdiscovery/nuclei/v2/pkg/core/executors.go:105 +0x4f8

Please provide a fix or work around for this

**Comment by tarunKoyalwar** [comment] 2023-05-03 11:41
Hii @knc331 , the issue is already resolved in dev branch and will be shipped in next bug fix release (soon) . you can install nuclei from dev branch with below command
```console
go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@dev
```

**Closed** 2023-05-03 20:47 UTC
Labels: Status: Completed, Type: Bug
