### ISSUE TITLE
Errors and pointer problems

### ISSUE THREAD

**Issue by hunter-00** [projectdiscovery/nuclei#1855] opened 2022-04-17 13:49 UTC
[ERR] Could not read nuclei-ignore file: open /root/.config/nuclei/.nuclei-ignore: no such file or directory
[WRN] Found 4 templates with syntax warning (use -validate flag for further examination)
[WRN] Found 7 templates with syntax error (use -validate flag for further examination)

====================================================

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfea151]

goroutine 2027716 [running]:
github.com/openrdap/rdap/bootstrap.(*Client).Lookup(0xc00ed94750, 0xc00ece3b60)
	/data/gopath/pkg/mod/github.com/openrdap/rdap@v0.9.1-0.20191017185644-af93e7ef17b7/bootstrap/client.go:310 +0x151
github.com/openrdap/rdap.(*Client).Do(0xc0035b00c0, 0xc008b75ce0)
	/data/gopath/pkg/mod/github.com/openrdap/rdap@v0.9.1-0.20191017185644-af93e7ef17b7/client.go:150 +0x4fd
github.com/projectdiscovery/nuclei/v2/pkg/protocols/whois.(*Request).ExecuteWithResults(0xc002f44000, {0xc00fb8bbd8, 0x7f3d34381150}, 0xc0108ff740, 0xc010b62210, 0xc00ece39b0)
	/data/gopath/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.8/pkg/protocols/whois/whois.go:89 +0xb9
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc00279a660, {0xc00fb8bbd8, 0x15})
	/data/gopath/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.8/pkg/protocols/common/executer/executer.go:68 +0x1ae
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x0, 0x0, {0xc00fb8bbd8, 0xffffffffffffffff})

**Comment by hunter-00** [comment] 2022-04-18 07:31
[ERR] Could not read nuclei-ignore file: open /root/.config/nuclei/.nuclei-ignore: no such file or directory
[WRN] Found 4 templates with syntax warning (use -validate flag for further examination)
[WRN] Found 7 templates with syntax error (use -validate flag for further examination)
![image](https://user-images.githubusercontent.com/67944000/163773141-0c80438b-dfd9-490a-8193-7e79d03109da.png)

**Comment by hunter-00** [comment] 2022-04-18 07:35
I didn't have these problems before the update, and what's the matter with the stuck for a long time after scanning
![image](https://user-images.githubusercontent.com/67944000/163773666-5d79b590-0183-4968-a4ae-5458b4d90451.png)

**Comment by jimen0** [comment] 2022-04-18 10:24
First panic looks like a duplicate of #1816 cc @ehsandeep

**Comment by ehsandeep** [comment] 2022-04-18 12:22
@jimen0 indeed, this is a duplicate of #1816, it looks like an issue with the underlying library in use, thanks for reporting this @hunter-00 closing this issue as we are tracking this at #1816

**Closed by ehsandeep** 2022-04-18 12:22 UTC
Labels: Type: Bug

**Comment by ehsandeep** [comment] 2022-04-18 12:24
> [ERR] Could not read nuclei-ignore file: open /root/.config/nuclei/.nuclei-ignore: no such file or directory [WRN] Found 4 templates with syntax warning (use -validate flag for further examination) [WRN] Found 7 templates with syntax error (use -validate flag for further examination) ![image](https://user-images.githubusercontent.com/67944000/163773141-0c80438b-dfd9-490a-8193-7e79d03109da.png)

@hunter-00 please file a new issue with setup details required to reproduce this issue, thank you.

**Comment by ehsandeep** [comment] 2022-04-20 14:45
@hunter-00 do you have any particular template that you can share to reproduce this crash or something you noticed on the random run?
