### ISSUE TITLE
Javascript postgres module cause memory leak

### ISSUE THREAD

**Issue by mastercho** [projectdiscovery/nuclei#5254] opened 2024-06-03 13:40 UTC
### Current Behavior:
Nuclei gets killed if you scan postgres ips on list longer than 50 in high severity

### Expected Behavior:
To not crash and finish scan
### Steps To Reproduce:

Site list was provided to @tarunKoyalwar for reproducing 

### Anything else:
Every details was send to @tarunKoyalwar discord and he is acknowledged about the issue 
![6c0ae4022db816685192830c748063b4](https://github.com/projectdiscovery/nuclei/assets/10222100/20ecc4ea-3f98-492b-9e40-f4d85b506855)

**Comment by zlgxzswjy** [comment] 2024-06-12 03:32
I found this problem, too！。During routine scan, I found that the memory was suddenly high, occupying more than 10 G, and then OOM appeared.After testing, it was found that this happens when ` -t javascript/enumeration/pgsql` is specified.

The reproduction process is as follows：
```bash
nuclei -u x.x.x.x:22 -t javascript/enumeration/pgsql
```

**Comment by Mzack9999** [comment] 2024-06-17 15:33
@mastercho @zlgxzswjy This should be fixed in https://github.com/projectdiscovery/nuclei/pull/5291 - Could you confirm if with that branch the issue is still reproducible? Thanks!

**Comment by mastercho** [comment] 2024-06-19 07:00
@Mzack9999 just tested, and still spikes pretty high all resources CPU and RAM at 80-90% but not to 100% as before to cause it crash

**Comment by mastercho** [comment] 2024-06-19 22:40
After short test on this PR we notice now is crashing even on mysql javascript module, we reverting changes until fixed...

**Comment by Mzack9999** [comment] 2024-06-20 12:41
@mastercho I am unable to reproduce the crash you are mentioning. Can you provide more context like the specifics of the machine you are testing on, CLI flags and targets?

I've just tested a full run of postgres modules on a class c network (254 hosts) of which 60 exposes a postgres instances, 10 having SSH exposed on postgres port (the cause of this memory leak, as the module kept reading on an internal buffer) and the other unresponsive. The memory peak I got was max 1Gb.

Feel free to reach out to mzack9999 on discord in case of sensitive info.

**Comment by mastercho** [comment] 2024-06-25 11:12
@zlgxzswjy hows in your end?

**Comment by zlgxzswjy** [comment] 2024-07-01 07:05
> @mastercho I am unable to reproduce the crash you are mentioning. Can you provide more context like the specifics of the machine you are testing on, CLI flags and targets?
> 
> I've just tested a full run of postgres modules on a class c network (254 hosts) of which 60 exposes a postgres instances, 10 having SSH exposed on postgres port (the cause of this memory leak, as the module kept reading on an internal buffer) and the other unresponsive. The memory peak I got was max 1Gb.
> 
> Feel free to reach out to mzack9999 on discord in case of sensitive info.

Yes, especially when scanning port 22 with these boards, there will be large-scale OOM, consuming tens of GB.

**Comment by zlgxzswjy** [comment] 2024-07-01 07:12
> @zlgxzswjy hows in your end?

From my verification results, it seems that the problem has been fixed
Repeat steps:
1. `go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@bugfix-5254-psql-mem`
2. `cd ~/go/bin && ./nuclei -u 47.101.201.147:22 -t /root/.local/nuclei-templates/javascript/enumeration/pgsql`
3. No more tens of gigabytes of memory, no more OOM

**Comment by zlgxzswjy** [comment] 2024-07-01 07:13
> @zlgxzswjy hows in your end?

From my verification results, it seems that the problem has been fixed
Repeat steps:

go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@bugfix-5254-psql-mem
cd ~/go/bin && ./nuclei -u X.X.X.X:22 -t /root/.local/nuclei-templates/javascript/enumeration/pgsql
No more tens of gigabytes of memory, no more OOM

**Comment by mastercho** [comment] 2024-07-01 08:17
Ok will run few tests on my side and will come back

**Comment by mastercho** [comment] 2024-07-02 13:11
i tried old list which is 64 subdomains and was causing crash before PR, did spikes memory to 80-90% as i said before but doesn't crash but if i went for double bigger list with 140 subdomains/ips its still spikes 100% and cause crash! just like in screenshot 
![83c1ffd6dbf307e336259a6313e224ca](https://github.com/projectdiscovery/nuclei/assets/10222100/53c8b5c5-907b-4ce3-bc19-4f32536f1a62)

This can't be considered as fix as nuclei must be able to scan bigger lists... Also dont ask me for Discord because your CEO said Discord is considered for PD offline chat and nothing must be discussed here and everything must be here...

**Comment by mastercho** [comment] 2024-07-02 19:28
I did build it from PR instead installing with `go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@bugfix-5254-psql-mem
` 

And now i have no issues with it tried on 3 different instances with 10GB ram each, so `go install` seems didn't update files every time, PR can be merged and issue closed

**Closed** 2024-07-08 11:38 UTC
Labels: Type: Bug
