### ISSUE TITLE
Kills wifi..

### ISSUE THREAD

**Issue by lopaknak** [projectdiscovery/nuclei#5593] opened 2024-09-02 17:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

Whenever i run nuclei even on low threads and -rl it still after a few minutes it crashes my whole wifi, it kills my home wifi/internet my wifi has 2 options it has 2.4G nd 5G and i usually use the 2.4G one cuz it has longer signal and better connection, and it literally kills that 2.4G so in the wifi options there is my wifi but you cant even connect to it even if you connect it will Not work, and the 5g works perfectly fine please fix this issue it has driven me crazy even when i run just a few templates with slow mode it still kills my wifi

### Expected Behavior

it should work and not kill my wifi 

### Steps To Reproduce

i do not know if this problem exists for everyone or not but it does for me,

1. Run nuclei on a directory containing a lot of nuclei templates without any -rl or -t option.
2. Run it for like 5 minutes.
3. Observe that wifi has crashed/killed

### Environment

```markdown
- OS: Windows 
- Nuclei: Nuclei Engine Version: v2.9.15
- Go: go version go1.22.3 linux/amd64
```

**Comment by MarcusMWilliams** [comment] 2024-09-02 17:59
Naked

**Comment by dogancanbakir** [comment] 2024-09-03 14:18
Duplicate of https://github.com/projectdiscovery/nuclei/issues/4781

**Closed by dogancanbakir** 2024-09-03 14:18 UTC
Labels: Type: Discussion
