### ISSUE TITLE
Output layout is confusing

### ISSUE THREAD

**Issue by laohuan12138** [projectdiscovery/nuclei#5287] opened 2024-06-12 02:51 UTC
### Nuclei version:

v3.2.8
### Current Behavior:

When using nuclei scanning, the console output is messy
![Snipaste_2024-06-12_10-44-52](https://github.com/projectdiscovery/nuclei/assets/42142726/49c0c832-ec4b-47cc-b3be-8fbf4519fcd4)

**Comment by dogancanbakir** [comment] 2024-06-12 07:54
duplicate of https://github.com/projectdiscovery/nuclei/issues/5122

**Closed by dogancanbakir** 2024-06-12 07:54 UTC
Labels: Type: Bug
