### ISSUE TITLE
Reporting to Github issues fails if the issue-label field is not set

### ISSUE THREAD

**Issue by 0xcrypto** [projectdiscovery/nuclei#1122] opened 2021-10-14 19:08 UTC
**Describe the bug**
For the following reporting configuration, nuclei fails to report with error `422 Validation Failed [{Resource:Label Field:name Code:missing_field Message:}]`

```yaml
allow-list:
    severity: info, low, medium, high, critical
github: 
    username: "0xcrypto"
    owner: "bb-research"
    token: "REDACTED"
    project-name: "hackberry_xyz"
```

**Nuclei version**
v2.5.2

**Screenshot of the error or bug**
![image](https://user-images.githubusercontent.com/6683856/137379877-93ddb54d-d527-4bf5-ad48-60011dee5c83.png)

**Comment by pmareke** [comment] 2021-10-15 09:04
I can take a look if there is not problem.

**Comment by forgedhallpass** [comment] 2021-10-15 09:23
@0xcrypto 
> Reporting to Github issues fails due to Message field missing 

Based on the error message I'd rather think the issue is around `label`s and not about a `message` field? If there are results to report, the logic tries to add the severity of the template as a `label` and you might not have permission to create new labels on the project.

**Comment by forgedhallpass** [comment] 2021-10-15 12:26
@0xcrypto it seems that the problem is that your reporting config file is missing the `issue-label` field. This field should be optional, and will be fixed soon. In the meantime you can work around it by setting an arbitrary value to it (e.g. nuclei)

**Comment by forgedhallpass** [comment] 2021-10-15 12:39
@pmareke the tasks we've discussed:
- [ ] do not send `nil` value if the `issue-label` is not set (both in case of GitHub and GitLab)
- [ ] update the `issue-label` documentation to better describe its purpose
- [ ] add validation for mandatory reporting configuration fields for all supported reporters
- [ ] the documentation of all configuration fields should state whether the attribute is optional or mandatory

The validations should happen as soon as possible, before any templates and should break the execution so that users could solve the issue before running the scans (otherwise it would require re-running everything, potentially even multiple times)

**Comment by pmareke** [comment] 2021-10-15 13:00
@o

> @pmareke the tasks we've discussed:
> 
> * [ ]  do not send `nil` value if the `issue-label` is not set (both in case of GitHub and GitLab)
> * [ ]  update the `issue-label` documentation to better describe its purpose
> * [x]  add validation for mandatory reporting configuration fields for all supported reporters
> * [x]  the documentation of all configuration fields should state whether the attribute is optional or mandatory
> 
> The validations should happen as soon as possible, before any templates and should break the execution so that users could solve the issue before running the scans (otherwise it would require re-running everything, potentially even multiple times)

The two first ones I'm not sure if they applied as the `nil` is not allowed not and the second one I really like the actual explanation.

**Comment by 0xcrypto** [comment] 2021-10-16 07:50
> @0xcrypto it seems that the problem is that your reporting config file is missing the `issue-label` field. This field should be optional, and will be fixed soon. In the meantime you can work around it by setting an arbitrary value to it (e.g. nuclei)

aah thanks. Lemme try a label in config.

**Comment by 0xcrypto** [comment] 2021-10-17 04:35
Thanks everyone! Adding `issue-label: "Nuclei"` fixed it.

**Comment by pmareke** [comment] 2021-10-17 05:34
> Thanks everyone! Adding `issue-label: "Nuclei"` fixed it. But maybe #822 no longer works.

Yes, we need to merge the dev implementation in master and then add the validations or in the other way arround.

Thanks for open the issue!

**Comment by pmareke** [comment] 2021-10-17 16:00
> @pmareke the tasks we've discussed:
> 
> * [ ]  make adding the severity as label optional by introducing a `severity-as-label` boolean field in both GitHub and GitLab options with associated description in the `issue-tracker-config.yaml` (e.g. "If set to true, it adds the matched template's severity as a label")
> * [x]  do not send `nil` value if the `issue-label` is not set (both in case of GitHub and GitLab)
> * [x]  update the `issue-label` documentation to better describe its purpose
> * [x]  add validation for mandatory reporting configuration fields for all supported reporters
> 
> * optional fields:
>   
>   * `github` and `gitlab`:
>     
>     * `base-url`
>     * `issue-label`
>     * `severity-as-label`
>   * `jira`
>     
>     * `cloud`
>     * `update-existing`
>   * `elasticsearch`
>     
>     * `ssl`
>     * `ssl-verification`
> 
> * [x]  the documentation of all configuration fields should explicitly mark optional attributes
> 
> The validations should happen as soon as possible, before any templates and should break the execution so that users could solve the issue before running the scans (otherwise it would require re-running everything, potentially even multiple times)

@forgedhallpass the PR has one ✅ , what do you want to do? Merge it and create another one or update the current one?

**Closed** 2021-10-21 01:30 UTC
Labels: good first issue, Status: Completed, Type: Bug, Hacktoberfest
