### ISSUE TITLE
Crash with proxy input (panic: send on closed channel)

### ISSUE THREAD

**Issue by shelu16** [projectdiscovery/nuclei#3513] opened 2023-04-06 14:29 UTC
Hi,
  I am facing an issue with the proxy 👍 
```console
github.com/projectdiscovery/nuclei/v2/internal/runner.runProxyConnectivity({{0xc0006becc0, 0x4}, {0x0, 0x0}, 0xc000696d50, {0xc0006bece4, 0x10}, {0xc0006becf4, 0x1}, {0x0, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1/internal/runner/proxy.go:85 +0xf9
created by github.com/projectdiscovery/nuclei/v2/internal/runner.processProxyList
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1/internal/runner/proxy.go:61 +0x298
```
Can you tell me why it is showing? my proxy is working properly, when i am try second time its working

**Comment by jimen0** [comment] 2023-04-06 14:43
@shelu16 - Could you please share the entire panic/trace, cmdline and proxy details? So far we are on a channel send operation: https://sourcegraph.com/github.com/projectdiscovery/nuclei@v2.9.1/-/blob/v2/internal/runner/proxy.go?L85

**Comment by tarunKoyalwar** [comment] 2023-04-07 16:14
@jimen0 , yeah so far looks like channel is closed with close(done) and goroutine is trying to send data to nil channel . Will fix this soon 
@shelu16 , can you paste entire stacktrace and not the portion of it . it helps to properly point out the bug

Thanks

**Comment by tarunKoyalwar** [comment] 2023-04-07 16:27
## Steps to reproduce
```console
go run -race . -u scanme.sh -proxy ~/test-templates/proxies.txt 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.2-dev

		projectdiscovery.io

==================
WARNING: DATA RACE
Read at 0x000107e3d190 by goroutine 41:
  github.com/projectdiscovery/nuclei/v2/internal/runner.runProxyConnectivity()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/proxy.go:84 +0x124
  github.com/projectdiscovery/nuclei/v2/internal/runner.processProxyList.func1()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/proxy.go:61 +0xa0

Previous write at 0x000107e3d190 by goroutine 54:
  github.com/projectdiscovery/nuclei/v2/internal/runner.assignProxyURL()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/proxy.go:108 +0xc4
  github.com/projectdiscovery/nuclei/v2/internal/runner.runProxyConnectivity()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/proxy.go:85 +0x188
  github.com/projectdiscovery/nuclei/v2/internal/runner.processProxyList.func1()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/proxy.go:61 +0xa0

Goroutine 41 (running) created at:
  github.com/projectdiscovery/nuclei/v2/internal/runner.processProxyList()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/proxy.go:61 +0xd0
  github.com/projectdiscovery/nuclei/v2/internal/runner.loadProxyServers()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/proxy.go:50 +0x420
  github.com/projectdiscovery/nuclei/v2/internal/runner.validateOptions()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/options.go:138 +0x180
  github.com/projectdiscovery/nuclei/v2/internal/runner.ParseOptions()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/options.go:89 +0x634
  main.main()
      /Users/tarun/Codebase/nuclei/v2/cmd/nuclei/main.go:69 +0x304

Goroutine 54 (running) created at:
  github.com/projectdiscovery/nuclei/v2/internal/runner.processProxyList()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/proxy.go:61 +0xd0
  github.com/projectdiscovery/nuclei/v2/internal/runner.loadProxyServers()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/proxy.go:50 +0x420
  github.com/projectdiscovery/nuclei/v2/internal/runner.validateOptions()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/options.go:138 +0x180
  github.com/projectdiscovery/nuclei/v2/internal/runner.ParseOptions()
      /Users/tarun/Codebase/nuclei/v2/internal/runner/options.go:89 +0x634
  main.main()
      /Users/tarun/Codebase/nuclei/v2/cmd/nuclei/main.go:69 +0x304
==================

```

**Comment by shelu16** [comment] 2023-04-07 16:32
Hi I set proxy on the config file and but some time working fine and suddenly crash or run time crash 


![image](https://user-images.githubusercontent.com/30596083/230644165-68ee71da-b174-4f4a-a032-2f79d9bc3afb.png)

**Comment by tarunKoyalwar** [comment] 2023-04-07 16:34
@shelu16 , thanks for verifying  but it helps if you share errors in above format ^ and they contain any sensitive info anyway. I was able to guess it as you can see in https://github.com/projectdiscovery/nuclei/issues/3513#issuecomment-1500439564 . anyway thanks . it will be fixed soon and available with next release

**Comment by shelu16** [comment] 2023-04-07 16:35
![image](https://user-images.githubusercontent.com/30596083/230644635-67ce103d-994c-4b0d-ba36-d08d4562c168.png)

**Comment by tarunKoyalwar** [comment] 2023-04-07 16:36
@shelu16 thanks , the error seems to be `panic: send on closed channle`

**Comment by shelu16** [comment] 2023-04-07 16:37
so it will be fix next update

**Closed** 2023-04-19 23:11 UTC
Labels: Status: Completed, Type: Bug
