### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by JaderKb** [projectdiscovery/nuclei#946] opened 2021-08-15 11:17 UTC
**Describe the bug**

There is a bug starting from version 2.4.0 (version 2.3.8 do not happen) related to Panic: runtime error: slice bounds out of range. I didn't find a pattern to it and sometimes it works with the same command.  What I am using:
./nuclei -l ./hosts.txt -stats -rl 20 -bs 20 -t ./temaplatesError/ -irr -markdown-export ./files/ -o ./results.txt --verbose
To test it I am using 200+ hosts and maybe you had to try it repeatedly.

Here are two template where it happens but there are more that trigger the same bug, I have tried it with different computers and OS versions.

**Templates Used**
**First**

```yaml
id: Arbitrary Text Injection

info:
  name: Arbitrary Text Injection
  author: Nikhil Kumar
  severity: Low
  tags:  injection

requests:
  - method: GET
    path:
      - "{{BaseURL}}/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM"

    matchers:
      - type: word
        words:
          - "!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM"
        part: body
```

**Second**

```yaml
id: header-reflection-body

info:
  name: Looking for reflected values from request headers
  author: panch0r3d
  severity: high

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"
      - "{{BaseURL}}/obviouslynotarealpathtoget404URLCanary1234"
      - "{{BaseURL}}/%%0D%%0|}+^$Aset-cookie%%20:mycookie=URLCKCanary1234;"
    redirects: true
    max-redirects: 5
    headers:
      User-Agent: "Mozilla UACanary12345"
      X-Forwarded-For: "panch0r3d.github.io?XFCanary12345"
      Referer: "RFcanary12345.comRF"
      Cookie: "CKCanary12345=qwertyCK"
      Origin: "ORCanary12345.comOR"
      x-request-id: "XRCanary12345"
      X-Correlation-ID: "XCIDCanary12345"
      from: "abc@FRcanary12345.comFR"
      pragma: "PRcanary12345"
      via: "VIACanary12345.comVIA"
      x-requested-with: "XRWCanary12345"
      x-att-deviceid: "XADCanary12345"
    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - ".*?(c|C)(a|A)(n|N)(a|A)(r|R)(y|Y)12345.*?"
        part: body
    extractors:
      - type: regex
        part: body
        regex:
          - "(c|C)(a|A)(n|N)(a|A)(r|R)(y|Y)12345.*?([\r\n]|[}]|[,][>])"
```

**Nuclei version**

starting in version 2.4.0

**Screenshot of the error or bug**

<img width="1315" alt="error2" src="https://user-images.githubusercontent.com/23459811/129476296-219e783b-e29f-46fe-8e84-d28e85409d36.png">
<img width="1350" alt="error1" src="https://user-images.githubusercontent.com/23459811/129476298-d86e0048-6488-4de5-822d-ab32a8aa33fe.png">

**Comment by ehsandeep** [comment] 2021-08-15 11:21
@JaderKb Can you try running this with the latest version of nuclei, i.e [2.4.3](https://github.com/projectdiscovery/nuclei/releases/tag/v2.4.3)?

**Comment by JaderKb** [comment] 2021-08-15 11:28
Actually I already tested it on all version and do not found the bug only on 2.3.8. I ran again now, here are the results:

**Version tested**

<img width="650" alt="version" src="https://user-images.githubusercontent.com/23459811/129476885-48477504-4c86-4f75-8af4-8f2c81700658.png">

**Error**

<img width="1278" alt="same" src="https://user-images.githubusercontent.com/23459811/129476899-5b4d8312-3aec-4de5-a654-337139dcbe2d.png">

**Comment by ehsandeep** [comment] 2021-08-15 11:58
@JaderKb unable to reproduce this on mac:- 

```bash
test $bat test1.yaml 
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: test1.yaml
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ id: Arbitrary Text Injection
   2   │ 
   3   │ info:
   4   │   name: Arbitrary Text Injection
   5   │   author: Nikhil Kumar
   6   │   severity: Low
   7   │   tags:  injection
   8   │ 
   9   │ requests:
  10   │   - method: GET
  11   │     path:
  12   │       - "{{BaseURL}}/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM"
  13   │ 
  14   │     matchers:
  15   │       - type: word
  16   │         words:
  17   │           - "!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM"
  18   │         part: body
  19   │ 
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

test $echo https://example.com | nuclei -t test1.yaml -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.4.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.4.3 (latest)
[INF] Using Nuclei Templates 8.4.5 (latest)
[INF] Using Interactsh Server https://interact.sh
[INF] Templates loaded: 1 (New: 25)
[VER] [Arbitrary Text Injection] Sent HTTP request to https://example.com/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[INF] No results found. Better luck next time!
```

**Comment by JaderOsiel** [comment] 2021-08-15 12:46
ok..use this list as input for hosts (Open DOD BB program):

https://dds.mil
https://staging.mayo.dds.mil
http://mayo.dds.mil
https://staging.mystatus.dds.mil
https://dns.dds.mil
https://indopacom.dowding.cuas.dds.mil
https://ss-mobile.dowding.cuas.dds.mil
https://southcom.dowding.cuas.dds.mil
https://cc.dowding.cuas.dds.mil
http://nbsd.dds.mil
https://staging.coronet.dds.mil
https://afrl.dowding.cuas.dds.mil
https://aus.dowding.cuas.dds.mil
https://ss-fl.dowding.cuas.dds.mil
https://nsse.dowding.cuas.dds.mil
https://doj.dowding.cuas.dds.mil
https://ss.dowding.cuas.dds.mil
https://staging.dawn.dds.mil
https://demo.dowding.cuas.dds.mil
https://navair-east.dowding.cuas.dds.mil
https://ncr.dowding.cuas.dds.mil
https://clonewars-experimental.dds.mil
https://sandia.dowding.cuas.dds.mil
https://staging.jerjerrod.dds.mil
https://navair-west.dowding.cuas.dds.mil
https://api.clonewars.dds.mil
https://mta-sts.dds.mil
https://clonewars.dds.mil
https://www.dns.dds.mil
https://clonewars-staging.dds.mil
https://defcon.dds.mil
https://api.clonewars-experimental.dds.mil
https://staging.yavin.dds.mil
https://staging.roadrunner.dds.mil
https://staging.padawan.dds.mil
https://www.dds.mil
https://www.staging.mayo.dds.mil
https://idp.preprod.dns.dds.mil
https://uk.dowding.cuas.dds.mil
https://usafe.dowding.cuas.dds.mil
https://subscriber.preprod.dns.dds.mil
https://subscriber.dns.dds.mil
https://api.clonewars-staging.dds.mil
https://staging.goose.dds.mil
https://idp.dns.dds.mil
https://staging.r4.dds.mil
https://staging.crait.dds.mil
https://ctc.dowding.cuas.dds.mil
https://staging.trando.dds.mil
https://connect.cuas.dds.mil

The first time, it happened on the second attempt, but to do it again I had to run 6 times.  I am using only the Arbitrary Text Injection template
<img width="1372" alt="erroragain" src="https://user-images.githubusercontent.com/76007855/129479079-8bab8eac-aac9-46b1-92ca-73f6b0322d46.png">

**Comment by ehsandeep** [comment] 2021-08-15 13:11
Worked well, but we will investigate this further based on the crash, Can you confirm your OS details? 

```
nuclei -t test1.yaml -l l.txt

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.4.3

		projectdiscovery.io

[INF] Using Nuclei Engine 2.4.3 (latest)
[INF] Using Nuclei Templates 8.4.5 (latest)
[INF] Using Interactsh Server https://interact.sh
[INF] Templates loaded: 1 (New: 25)
[2021-08-15 18:37:56] [Arbitrary Text Injection] [http] [] https://doj.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:56] [Arbitrary Text Injection] [http] [] https://cc.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:56] [Arbitrary Text Injection] [http] [] https://ctc.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:56] [Arbitrary Text Injection] [http] [] https://navair-west.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:56] [Arbitrary Text Injection] [http] [] https://navair-east.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:56] [Arbitrary Text Injection] [http] [] https://demo.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:56] [Arbitrary Text Injection] [http] [] https://indopacom.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:56] [Arbitrary Text Injection] [http] [] https://ncr.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:56] [Arbitrary Text Injection] [http] [] https://nsse.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:57] [Arbitrary Text Injection] [http] [] https://ss-fl.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:57] [Arbitrary Text Injection] [http] [] https://ss-mobile.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:57] [Arbitrary Text Injection] [http] [] https://aus.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:57] [Arbitrary Text Injection] [http] [] https://ss.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:58] [Arbitrary Text Injection] [http] [] https://sandia.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:58] [Arbitrary Text Injection] [http] [] https://afrl.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:58] [Arbitrary Text Injection] [http] [] https://subscriber.preprod.dns.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:58] [Arbitrary Text Injection] [http] [] https://usafe.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:58] [Arbitrary Text Injection] [http] [] https://subscriber.dns.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:37:59] [Arbitrary Text Injection] [http] [] https://southcom.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
[2021-08-15 18:38:00] [Arbitrary Text Injection] [http] [] https://uk.dowding.cuas.dds.mil/!!!ATENTION!!!_This_site_is_on_Maintenance_please_go_to_WWW.EVIL.COM
```

**Comment by JaderKb** [comment] 2021-08-15 13:52
ok.. always with that host list, i used 3 different instances of Ubuntu - 1 Kali and 1 OSX (all had the same problem)

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Linux ip-XXXXX XXXXX-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Tested with Kali also using the following template with the same hosts lists:

**template**

id: developer-notes

info:
  name: Developer Notes
  author: panch0r3d
  severity: info

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"
    redirects: true
    max-redirects: 5
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0"
    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - ""
          - "/[*][*](.*?)[*][*]/"
        part: body
      - type: status
        status:
          - 200
          - 301
          - 302
    extractors:
      - type: regex
        part: body
        regex:
          - ""
          - "/[*][*](.*?)[*][*]/"
         
<img width="1786" alt="Kali" src="https://user-images.githubusercontent.com/23459811/129480613-06c97742-cf18-4104-bcf5-4f949454aa9a.png">

Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2021.2
Codename:       kali-rolling
Linux kali 5.10.0-kali7-amd64 #1 SMP Debian 5.10.28-1kali1 (2021-04-12) x86_64 GNU/Linux


Using MAC I also got error with developers_nome using the same host file

![mac](https://user-images.githubusercontent.com/23459811/129480763-746fa18c-2f5b-40bb-9a62-cc39de245acb.png)


MAC details
Darwin BR0C02FQ0K9MD6M 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
Mac Os Big Sour 11.3.1

**Comment by ehsandeep** [comment] 2021-08-16 17:47
@JaderKb should be fixed in dev version with the following PR https://github.com/projectdiscovery/nuclei/pull/949

**Comment by JaderKb** [comment] 2021-08-16 18:44
great! tks

**Closed** 2021-09-01 14:56 UTC
Labels: Status: Completed, Type: Bug
