### ISSUE TITLE
Windows prebuilt binary doesn't work and no compilation instruction

### ISSUE THREAD

**Issue by Zeokat** [projectdiscovery/nuclei#46] opened 2020-04-27 13:16 UTC
I tested the prebuilt binary into my Windows 7 x64 machine and the binary doesn't work.

It return an error saying that thiue version of the program isn't compatible with my Windows version.

So, Nuclei doesn't support Windows?

I also want to add, that have compilation instructions will be nice.

**Comment by bauthard** [comment] 2020-04-27 13:47
Hi @Zeokat, 

This is a duplicate of https://github.com/projectdiscovery/nuclei/issues/20, Can you check and share the requested information.

**Closed by bauthard** 2020-04-27 13:47 UTC
