### ISSUE TITLE
nuclei3.0.1：Could not run nuclei: no templates provided for scan

### ISSUE THREAD

**Issue by mortals-tx** [projectdiscovery/nuclei#4289] opened 2023-10-25 05:34 UTC
root@kali:~/tools/nuclei# ./nuclei -u http://10.50.0.63:8080/ -t ./nuclei-templates-9.6.7  

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.1

		projectdiscovery.io

[ERR] Could not find template './nuclei-templates-9.6.7': could not find template file: no such path found: ./nuclei-templates-9.6.7
[INF] Current nuclei version: v3.0.1 (latest)
[INF] Current nuclei-templates version: v9.6.7 (latest)
[INF] Targets loaded for current scan: 1
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan

![8E5A267C-9A8D-43a9-A250-5A9281AC299C](https://github.com/projectdiscovery/nuclei/assets/54280251/59754994-cb7c-4108-b57f-2db2858b2a1f)

**Comment by ehsandeep** [comment] 2023-10-25 05:40
@mortals-tx this is duplicate of https://github.com/projectdiscovery/nuclei/issues/4258 and being fixed here - https://github.com/projectdiscovery/nuclei/pull/4284

**Closed by ehsandeep** 2023-10-25 05:40 UTC
Labels: Type: Enhancement
