### ISSUE TITLE
[issue] Exclude or ignore not running with -l parameter

### ISSUE THREAD

**Issue by six2dez** [projectdiscovery/nuclei#431] opened 2020-12-01 11:44 UTC
**Exclude or ignore not running with -l parameter**
I'm trying to exclude "tech-detect" and other info templates from output for a list of targets.
For this I tried with `-exclude technologies`, `-severity low,medium,high,critical` and set in .nuclei-ignore as `technologies/`.
With single target works perfect.

**Nuclei version**
2.2.0

**Screenshot of the error or bug**

`-silent` set just to fit the image, with list not work, single target OK.

![imagen](https://user-images.githubusercontent.com/24670991/100736249-c703dd00-33d2-11eb-8f35-3dadcd552ad7.png)

**Comment by bauthard** [comment] 2020-12-01 14:03
@six2dez, You are also running workflows in your scan, and tech detects templates also being executed from workflows, so you can consider excluding workflow, this is not a bug, so closing this issue.

**Closed by bauthard** 2020-12-01 14:03 UTC
