### ISSUE TITLE
 uniq and sort helper function

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#2305] opened 2022-07-18 10:36 UTC
### Please describe your feature request:
New helper functions:

- [x] sort
- [x] uniq

Helper example:

```yaml
{{sort(list)}}
{{uniq(list)}}
```

The list is an array of data in a variable.

Exampel template:

```yaml
requests:
  - method: GET
    path:
      - "{{RootURL}}"
      - "{{RootURL}}{{uniq(endpoint)}}/phpinfo.php"

    extractors:
      - type: regex
        name: endpoint
        group: 1
        regex:
          - '(/([a-z0-9A-Z-_.]+/)*([a-z0-9A-Z-_]+)/)'
        internal: true

    iterate-all: true
    redirects: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "phpinfo()"
```

**Comment by brenocss** [comment] 2022-07-18 16:31
https://github.com/projectdiscovery/nuclei/issues/2025 resolve/resolve_all dsl would be great

**Comment by mjkim610** [comment] 2022-07-29 07:01
@ehsandeep, if this issue is open, please assign it to me. I will take a look :)

**Comment by forgedhallpass** [comment] 2022-07-29 12:28
@brenocss 

> #2025 resolve/resolve_all dsl would be great

You can follow [this](https://github.com/projectdiscovery/nuclei/issues/2341) dedicated ticket for it.

**Comment by forgedhallpass** [comment] 2022-07-29 12:29
@mjkim610 the issue is now assigned to you. Please make sure to follow my comments [above](https://github.com/projectdiscovery/nuclei/issues/2305#issuecomment-1187426430) and happy coding :)

**Comment by mjkim610** [comment] 2022-07-29 17:04
Tasks:
- [ ] `sort(list)`
- [ ] `uniq(list)`
- [ ] `sort(string)` : https://github.com/projectdiscovery/nuclei/pull/2372 (WIP)
- [ ] `uniq(string)`

**Comment by mjkim610** [comment] 2022-08-08 07:06
@ehsandeep @Mzack9999 @forgedhallpass I have a question related to this issue.
Can the helper functions have return types other than string?

While working on this, I thought that I could simply return space-separated string to represent uniqed and sorted lists. But with that implementation, when we chain these commands, it doesn't work as expected because spaces are considered runes rather than separators.

```
sort(uniq("aabbbcddeeee")):      abcde
--- FAIL: TestDslExpressions (1.02s)
    --- FAIL: TestD

**Comment by Mzack9999** [comment] 2022-08-08 07:21
@mjkim610 DSL functions usually have `interface{}` return type, so it's possible to return the slice of strings directly. The correct type will be inferred later via reflection. The only problem I think might arise if the DSL function is the last in a call chain, and its output needs to be used within a protocol request (e.g. `{{sort("a","b")}}`) but I think it should be enough to prefix it with `to_string` (`{{to_string(sort("a","b"))}}`)

**Comment by forgedhallpass** [comment] 2022-08-08 13:45
If the input is a slice (array), then it is expected for the output to also be a slice.
There is already a `join` function that accepts a separator and a list of elements, hence it should not be a problem.

**Comment by mjkim610** [comment] 2022-08-27 01:48
Thanks for the tip, @Mzack9999 and @forgedhallpass !

I updated https://github.com/projectdiscovery/nuclei/pull/2372 and requested your reviews :)

**Comment by mjkim610** [comment] 2022-08-27 06:53
PR for `uniq()` created: https://github.com/projectdiscovery/nuclei/pull/2498

**Closed** 2022-11-14 22:11 UTC
Labels: Status: Completed, Type: Enhancement
