### ISSUE TITLE
Variables are not used when given in dynamic auth 

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4999] opened 2024-04-05 18:31 UTC
### Discussed in https://github.com/projectdiscovery/nuclei/discussions/4991

<div type='discussions-op-text'>

<sup>Originally posted by **mikemicky4321** April  4, 2024</sup>
Hello Team,
We would like to implement authenticated based scan for an application like OWASP Juice shop. But we are receiving below error. Please find attached yaml files both login.yaml and secrets.yaml. I am getting below error. Could you please help us?

![image](https://github.com/projectdiscovery/nuclei/assets/115986628/bb1eb632-f32b-4808-8e5f-ebf0f5612a22)

[yamlfiles.zip](https://github.com/projectdiscovery/nuclei/files/14872886/yamlfiles.zip)

![image](https://github.com/projectdiscovery/nuclei/assets/115986628/0a3aec6f-a668-447a-b946-46e1679e1fa8)
</div>

**Comment by stevieg27** [comment] 2024-06-20 12:51
@tarunKoyalwar is there any timeline for this fix. Thnaks

**Comment by k4z4n0v4** [comment] 2024-10-25 11:32
I'll try and work on this.  Is someone currently assigned?

**Comment by ehsandeep** [comment] 2024-10-25 11:35
@k4z4n0v4 thank you, I've assigned this issue to you.

**Comment by k4z4n0v4** [comment] 2024-10-25 12:48
Okay so the issue is either in improper documentation or improper implementation. The `variables` is of type `KV`, which in [file.go](https://github.com/projectdiscovery/nuclei/blob/49811d24a12d5894f6c0bfc3f3e9262745e568c1/pkg/authprovider/authx/file.go#L150) is set to be unmarshalled from yaml by names "key" and "value", while the documentation says to specify the variables by "name" and "value", this results in creation of variables in nuclei's context without a key, as it can not find the "key" element.

So if the dynamic auth is set like:
```yaml
dynamic:
  - template: /path/to/login.yaml
    variables:
      - key: 'username'
        value: user@name.com
      - key: password
        value: admin123
```
instead of:
```yaml
dynamic:
  - template: /path/to/login.yaml
    variables:
      - name: 'username'
        value: user@name.com
      - name: password
        value: admin123
```
It works.

Shall i modify the documentation or change it so that the "variables" expects a "name" as its keys?

**Comment by tarunKoyalwar** [comment] 2024-10-25 13:08
hey @k4z4n0v4 , thank you for pointing out , looks like there was a minor hiccup with documentation which resulted in this issue , feel free to update the documentation and other references where `name` is mentioned instead of `key` , this is the docs repo btw https://github.com/projectdiscovery/docs

**Comment by k4z4n0v4** [comment] 2024-10-25 13:27
Thanks for amazing work. https://github.com/projectdiscovery/docs/pull/95

**Comment by ehsandeep** [comment] 2024-10-25 13:37
Thank you @k4z4n0v4 for taking time to review the code and fix the docs.

@vx-sec see https://github.com/projectdiscovery/docs/pull/95 to make changes in config file to get it working.

**Comment by ehsandeep** [comment] 2024-10-25 13:38
Closing as it was issue with docs fixed in https://github.com/projectdiscovery/docs/pull/95

**Closed by ehsandeep** 2024-10-25 13:38 UTC
Labels: DAST
