### ISSUE TITLE
Nuclei is broken after running for some hours

### ISSUE THREAD

**Issue by motaha22** [projectdiscovery/nuclei#3783] opened 2023-06-05 11:09 UTC
When I run nuclei to scan for like 3000 host, it broke after some hours with this error

![image](https://github.com/projectdiscovery/nuclei/assets/40707762/f9afe275-9678-4db8-ae7c-73f5de522c89)

I tried to run it in another vps from a different vendor and the same issue happened.

And this is the version of  nuclei with go 

![image](https://github.com/projectdiscovery/nuclei/assets/40707762/31ca07fb-c4a0-48bd-b92c-1a427acb27c6)

and the command I ran is 

cat live.txt|nuclei  -t ~/nuclei-templates/ -es info --etags ssl --stats -o result1.txt

**Comment by Mzack9999** [comment] 2023-06-22 08:30
@mastercho This looks like a duplicate of https://github.com/projectdiscovery/nuclei/issues/3797 - It should be fixed in next release (and already in `dev` branch) with https://github.com/projectdiscovery/utils/pull/176

**Closed** 2023-06-26 20:35 UTC
Labels: Status: Completed, Type: Bug
