### ISSUE TITLE
error in install  nuclei 

### ISSUE THREAD

**Issue by 00SoCRaT00** [projectdiscovery/nuclei#1377] opened 2021-12-15 20:03 UTC

**Comment by forgedhallpass** [comment] 2021-12-15 20:04
Duplicate of #1376

**Closed by forgedhallpass** 2021-12-15 20:04 UTC
Labels: duplicate, Type: Bug

**Comment by 00SoCRaT00** [comment] 2021-12-15 20:08
when i run as root 
GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei  
i got this error 
go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.5/internal/runner/update.go:27:2: //go:build comment without // +build comment
![image](https://user-images.githubusercontent.com/83826259/146257301-41799fa4-e70a-4b32-8ec2-da1f4c6cae21.png)

**Comment by 00SoCRaT00** [comment] 2021-12-15 20:08
please any one help
