### ISSUE TITLE
-headless exception :" An existing connection was forcibly closed by the remote host."

### ISSUE THREAD

**Issue by p0mel0** [projectdiscovery/nuclei#2389] opened 2022-08-03 08:17 UTC
### Current Behavior: When I use the -headless parameter, the following error is reported

```
D:\Nuclei\nuclei.exe -v -id dvwa-headless-automatic-login -headless -u http://localhost/DVWA/ -sb

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.5

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.7.5 (latest)
[INF] Using Nuclei Templates 9.1.3 (latest)
[INF] Templates added in last update: 40
[INF] Templates loaded for scan: 1
[WRN] [dvwa-headless-automatic-login] Could not execute request for http://localhost/DVWA/: could get html element: read tcp 127.0.0.1:53634->127.0.0.1:53632: wsarecv: An existing connection was forcibly closed by the remote host.
[INF] No results found. Better luck next time!
```
### Solution
<!--
Example: steps to reproduce the behavior:
```
1. Run 'nuclei -t ... -u ..'
2. See error...
-->
it maybe a browser compatibility issue，I solved it by following the steps below
```
1.Find the browser for nuclei download
2.Right-click on the icon to open the drop-down menu.
3.Click Properties.
4.Navigate to the Compatibility tab.
5.Look for Run this program in compatibility mode for under the Compatibility mode option and check the box.
6.Under it, click the drop-down arrow and select Windows 8.
7.At the bottom, click Change settings for all users.
8.Now, click Apply.
```
Reference: https://www.windowsdispatch.com/fix-google-chrome-status-invalid-image-hash-error/
### Anything else:
<!-- Links? References? Screenshots? Anything that will give us more context about the issue that you are encountering! -->
When you use the `-sc` parameter to use a local browser, you may also encounter this problem, the solution is the same

**Comment by tarunKoyalwar** [comment] 2022-12-02 15:13
@p0mel0 ,are you still able to reproduce this issue . It works fine on linux/mac . and it be related to `docker` . 

1. do you get same error with the latest version 2.7.9 ??
2. Can you try this on any other website and share results . Use command
```sh
  nuclei -u https://projectdiscovery.io  -stats -headless -id screenshot
```

**Comment by ehsandeep** [comment] 2022-12-02 15:49
@tarunKoyalwar could be related to https://github.com/projectdiscovery/retryabledns/pull/66 and fixed.

**Comment by tarunKoyalwar** [comment] 2022-12-02 15:51
@ehsandeep  are you able to reproduce it ?? I don't have windows available now .

**Comment by Mzack9999** [comment] 2022-12-13 13:48
This is not reproducible anymore on windows AMD64:
```console
> go run .  -id dvwa-headless-automatic-login -headless -u http://localhost/DVWA/ -sb

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.4-dev

                projectdiscovery.io

[INF] Using Nuclei Engine 2.8.4-dev (development)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] No results found. Better luck next time!
```

Unable to reproduce - I'm closing the issue and will reopen it if similar problems get reported.

**Closed by Mzack9999** 2022-12-13 13:48 UTC
Labels: Priority: Low, Type: Bug, Investigation
