### ISSUE TITLE
[issue] piped list and -l option not working

### ISSUE THREAD

**Issue by dogasantos** [projectdiscovery/nuclei#383] opened 2020-10-24 22:38 UTC
**Describe the bug**
nuclei doesn't work against a list of  targets using -l option or piped input.
It only works in single targets either via pipe or -target option.

It finishes immediately with no processing time, nor a sigle request sent.

The target file has 200 lines (wc -l).

**Nuclei version**
v2.1.1

**Screenshot of the error or bug**
![1](https://user-images.githubusercontent.com/4156021/97094959-35b18600-1630-11eb-9ad1-83444ddbd456.PNG)

![file-pipe](https://user-images.githubusercontent.com/4156021/97094963-39dda380-1630-11eb-87ae-197b7bef34a3.PNG)

![single-piped-works](https://user-images.githubusercontent.com/4156021/97094964-3cd89400-1630-11eb-814f-21d519f5e579.PNG)
![single-target](https://user-images.githubusercontent.com/4156021/97094966-3ea25780-1630-11eb-91fd-834a9174826a.PNG)

**Comment by Princ3g** [comment] 2020-10-25 13:00
same here! I am trying to follow few videos and this doesnt work, even this command doesn't seem to work **echo "https://att.com" | nuclei -t /root/nuclei-templates/cves/ -c 50 -o basic-recon/nuclei-output.txt**, it shows this error : **"flag provided but not defined: -c"**, please do help :) and thank you for posting similar query

**Comment by bauthard** [comment] 2020-10-25 18:44
@dogasantos Locally this works for me, Can you share the content of `razer.com.web`?

@Princ3g you are using the master version, active in the development, you can use last stable version from here https://github.com/projectdiscovery/nuclei/releases

**Comment by Princ3g** [comment] 2020-10-26 18:02
> @dogasantos Locally this works for me, Can you share the content of `razer.com.web`?
> 
> @Princ3g you are using the master version, active in the development, you can use last stable version from here https://github.com/projectdiscovery/nuclei/releases

Thank you very much, it worked with older version. Finally, I thought I wont be able to use a good tools before I even begin to use it properly. :+1:

**Comment by dogasantos** [comment] 2020-10-26 18:12
hey @bauthard sure thing!

root@kalicloud2:~/_bhunter/razer/razer.com# file razer.com.web 
razer.com.web: ASCII text
root@kalicloud2:~/_bhunter/razer/razer.com# wc -l razer.com.web 
200 razer.com.web

I don't believe that's an encoding issue or anything like that, but to be faithful, i've gzipped the file (attached)

For a doublecheck, here is the text content:
https://app-assets.razer.com 
https://api-s2.phoenix.razer.com
https://5s.razer.com
https://abyssus.razer.com
https://ap3.razer.com
https://amp.razer.com
https://apps-staging.razer.com
https://apps-launcher-staging.razer.com
https://apps-api-staging.razer.com
https://apps-cortex-staging.razer.com
https://apps-releasenotes-staging.razer.com
https://ca.deals.razer.com
https://ccv2-s1.phoenix.razer.com
https://backoffice-s1.phoenix.razer.com
https://ccv2-s3.phoenix.razer.com
https://br.deals.razer.com
https://ccv2-d1.phoenix.razer.com
https://api-p1.phoenix.razer.com
https://api-s3.phoenix.razer.com
https://backoffice-s3.phoenix.razer.com
https://cf.razer.com
https://api-s1.phoenix.razer.com
https://codigosteam.gold.razer.com
http://autodiscover.razer.com
https://api.razer.com
https://api-d1.phoenix.razer.com
http://autodiscover.pay.razer.com
https://cj.razer.com
https://cmssvc.gold.razer.com
https://console.gold.razer.com
https://cms.gold-sandbox.razer.com
https://de.razer.com
https://dl.razer.com
https://cortex-gso.razer.com
https://api.us-west-2.m.razer.com 
https://de.deals.razer.com
https://api.us-west-2.in.m.razer.com
https://cortex-staging.razer.com
https://careers.razer.com
https://admin.mobile.razer.com
https://ec-qa.razer.com
https://ec.razer.com
https://api.us-west-2.op.m.razer.com
https://fn.razer.com
https://fintech.razer.com
https://fr.razer.com
https://fr.deals.razer.com
https://enterpriseenrollment.razer.com
https://api-dev.pay.razer.com
https://dev.mobile.razer.com
https://cn.razer.com
https://ecommerce.pay.razer.com
https://gb.deals.razer.com
https://develop.mobile.razer.com
https://dev.m.razer.com
https://appcasts.razer.com
https://developer.mobile.razer.com
https://gold-sandbox.razer.com
https://deals.razer.com
https://harmony.razer.com
https://flagship-gaming.razer.com
https://greatideas.razer.com
https://ingress-p.phoenix.razer.com
https://global.zgold-qa.razer.com
https://gamestore.razer.com
https://game.razer.com
https://legacy.razer.com
https://7e-admin.pay-dev.razer.com
https://lol.razer.com
https://kb.razer.com
https://7e-api.pay-dev.razer.com
https://admin-api-uat-sg.pay.razer.com
https://analytics-sg.pay.razer.com
https://app.pay.razer.com
https://api-uat-sg.pay.razer.com
https://api-sg.pay.razer.com
https://developer.razer.com
https://apps.pay.razer.com
https://media.gold.razer.com
https://customs.razer.com
https://api-stg.pay.razer.com
https://api.merchant.razer.com
https://lvlup.razer.com
https://media-external.gold.razer.com
https://admin-qa.7e.pay.razer.com
https://merchantvoucher.gold.razer.com
https://merchant.zgold-qa.razer.com
https://miniapp.zgold-qa.razer.com
https://media.gold-sandbox.razer.com
https://dcbgw.gold.razer.com
https://merchant.zvault.razer.com
https://music.razer.com
https://maxine-staging.razer.com
https://jp-store.razer.com
https://ecommerce-uat-sg.pay.razer.com
https://eform.merchant.razer.com
https://lyncdiscover.razer.com
https://gift-card-my.pay.razer.com
https://oauth2-mgm.razer.com
https://oauth2.razer.com
https://mobile.razer.com
https://paychannel.zgold-qa.razer.com
https://pay.zgold-qa.razer.com
https://m.razer.com
https://pay.zvault.razer.com
https://image.mailer.gold.razer.com
https://new-uat.razer.com
https://irmedia.razer.com
https://pay.razer.com
https://press.razer.com
https://lead.merchant.razer.com
https://hello.merchant.razer.com
https://prod.mobile.razer.com
https://prerc.mobile.razer.com
https://preprod.m.razer.com 
https://mask-my.pay.razer.com
https://promotions.zgold-qa.razer.com
http://push.razer.com
https://preprod.mobile.razer.com
https://media.zgold-qa.razer.com
https://razer-alexa.razer.com
https://razer-alexa-dev.razer.com
https://razer-alexa-staging.razer.com
https://qa.mobile.razer.com
https://movie-sg.pay.razer.com
https://ragnarok.razer.com
https://merchant.razer.com
https://movie-uat-sg.pay.razer.com
https://razer.com
https://reward.gold-sandbox.razer.com
https://reward.zgold-qa.razer.com
https://rw.zvault.razer.com
https://razer-id.razer.com
https://rc.m.razer.com
https://portal.merchant.razer.com
https://repo2.m.razer.com
https://repo.m.razer.com
https://rc.mobile.razer.com
https://pay.merchant.razer.com
https://silvermerchant.gold.razer.com
https://retail.mobile.razer.com
https://sandbox.mobile.razer.com
https://silvermerchant.zgold-qa.razer.com
https://merchant.gold-sandbox.razer.com
https://staging.mobile.razer.com
https://sitemap.razer.com
https://storefront-p1.phoenix.razer.com
https://storefront-d1.phoenix.razer.com
https://sip.razer.com
https://storefront-s2.phoenix.razer.com
https://sandbox.merchant.razer.com
https://storefront-s1.phoenix.razer.com
https://sbx-vip.merchant.razer.com
https://storefront-s3.phoenix.razer.com
https://sea-services.gold.razer.com
https://sea-api.gold.razer.com
https://store.razer.com
https://support.pay-dev.razer.com
https://support.tipstream.razer.com
https://support.harmony-staging.razer.com
https://status.razer.com
https://tipstream-api.razer.com
https://tipstream-support.razer.com
https://thumbor-prod.phoenix.razer.com
https://tipstream.razer.com
https://reseller.gold-sandbox.razer.com
https://tipstream-media.razer.com
https://topupapi.zgold-qa.razer.com
https://tipstream-media-staging.razer.com
https://training.razer.com
https://uat-ss-legacy.razer.com
https://subscribe.razer.com
https://thumbor-nonprod.phoenix.razer.com
https://status.merchant.razer.com
https://uatapi.merchant.razer.com
http://api-staging.razer.com
http://ces.razer.com
https://webhookapi.gold.razer.com
http://codigosteam-test.gold.razer.com
https://work.razer.com
https://uat-vip.merchant.razer.com
http://admin-stg.pay.razer.com
http://harmony-staging-api.razer.com
http://harmony-staging.razer.com
https://www2.zgold-qa.razer.com
https://www2.razer.com
http://id-staging.razer.com
https://www.razer.com
https://yammer.razer.com
https://www.tipstream.razer.com
https://uat-ss.razer.com
https://zpay.gold-sandbox.razer.com
https://zvault.razer.com
http://wiki.razer.com
https://web-uat-sg.pay.razer.com
https://web-qa.7e.pay.razer.com
http://razerid-dev.razer.com
http://razerid-prod.razer.com
http://sg.pay.razer.com
http://tipstream-support-staging.razer.com


[a.gz](https://github.com/projectdiscovery/nuclei/files/5440601/a.gz)

**Comment by dogasantos** [comment] 2020-10-26 18:12
PS: Ty for looking into this
Let me know if you need anything else, please

**Comment by bauthard** [comment] 2020-10-31 06:45
@dogasantos I've tried the same with your list and I can see the expected results on my side.

```sh
root@test:~/nuclei/v2/cmd/nuclei# nuclei -version

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.1.1

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Current Version: 2.1.1

root@test:~/nuclei/v2/cmd/nuclei# wc rz.txt 
200 rz.txt

root@test:~/nuclei/v2/cmd/nuclei# less rz.txt | head -n 5
https://app-assets.razer.com
https://api-s2.phoenix.razer.com
https://5s.razer.com
https://abyssus.razer.com
https://ap3.razer.com

root@test:~/nuclei/v2/cmd/nuclei# nuclei -l rz.txt -t ~/nuclei-templates/technologies/ -silent 
[waf-detect:shadowd] [http] https://amp.razer.com/
[waf-detect:apachegeneric] [http] https://amp.razer.com/
[waf-detect:nginxgeneric] [http] https://amp.razer.com/
[waf-detect:shadowd] [http] https://ap3.razer.com/
[waf-detect:apachegeneric] [http] https://ap3.razer.com/
[waf-detect:nginxgeneric] [http] https://ap3.razer.com/
[waf-detect:apachegeneric] [http] https://ccv2-s1.phoenix.razer.com/
[waf-detect:aws] [http] https://app-assets.razer.com/
[waf-detect:cloudflare] [http] https://app-assets.razer.com/
[what-waf-detect:aws] [http] https://app-assets.razer.com/
[what-waf-detect:cloudflare] [http] https://app-assets.razer.com/
[waf-detect:ats] [http] https://ca.deals.razer.com/
[waf-detect:nginxgeneric] [http] https://ca.deals.razer.com/
[waf-detect:shadowd] [http] https://abyssus.razer.com/
[waf-detect:apachegeneric] [http] https://abyssus.razer.com/
[waf-detect:nginxgeneric] [http] https://abyssus.razer.com/
[waf-detect:shadowd] [http] https://5s.razer.com/
[waf-detect:apachegeneric] [http] https://5s.razer.com/
[waf-detect:nginxgeneric] [http] https://5s.razer.com/
[waf-detect:aws] [http] https://apps-staging.razer.com/
[waf-detect:cloudflare] [http] https://apps-staging.razer.com/
[s3-detect] [http] https://app-assets.razer.com/%%c0
^C
```

**Comment by dogasantos** [comment] 2020-11-03 14:45
That's the method used to generate the file.
If you just copy the text content here, you should be able to run nuclei just fine.

I've tested with 2 different methods:

opt1) 
cat hosts.txt | httprobe > hosts.web

opt2) 
cat hosts.txt | httpx -title -content-length -status-code -o hosts.httpx
cat hosts.httpx | cut -f1 -d '[' >  hosts.web

using opt1 (httprobe), nuclei works just fine with -l hosts.web
using opt2 (httpx), nuclei won't be able to run.

Both files are unix formated text files, both have ending \n lines
For some reason, option2 causes the issue

**Comment by dogasantos** [comment] 2020-11-03 15:01
on strace, I can see that for some reason, nuclei is able to see the \n, but it won't parse it as a new line:

`[pid 398811] <... read resumed>"https://app-assets.razer.com \nht"..., 4096) = 4096
[pid 398812] nanosleep({tv_sec=0, tv_nsec=320000},  <unfinished ...>
[pid 398811] read(3, "er.com \nhttps://razer-id.razer.c"..., 4075) = 2261
[pid 398811] read(3, "", 4096)          = 0
[pid 398811] close(3)                   = 0
[pid 398811] newfstatat(AT_FDCWD, "/usr/share/nuclei-templates/files/phpinfo.yaml", {st_mode=S_IFREG|0644, st_size=643, ...}, 0) = 0
[pid 398812] <... nanosleep resumed>NULL) = 0
[pid 398811] write(2, "[\33[34mINF\33[0m] Loading templates"..., 36 <unfinished ...>`

On httprobe generated file, nuclei is able to parse the \n just fine and then run the template.

**Comment by bauthard** [comment] 2020-11-03 15:08
@dogasantos I can confirm the issue, there is something wrong that needs to be fixed, thank you for sharing detailed information. 

```
httpx -title -content-length -status-code -no-color | cut -f1 -d '['
```

```
chaos -d hackerone.com | httpx -title -content-length -status-code -no-color | cut -f1 -d '[' | nuclei -t technologies/tech-detect.yaml -v

  
[http-request] Sent for [tech-detect] to https://resources.hackerone.com 
[http-request] Sent for [tech-detect] to https://mta-sts.forwarding.hackerone.com 
[http-request] Sent for [tech-detect] to https://mta-sts.hackerone.com 
[http-request] Sent for [tech-detect] to https://docs.hackerone.com 
[http-request] Sent for [tech-detect] to https://support.hackerone.com 
[http-request] Sent for [tech-detect] to https://www.hackerone.com 
[http-request] Sent for [tech-detect] to https://mta-sts.managed.hackerone.com 
[http-request] Sent for [tech-detect] to https://api.hackerone.com 
[WRN] [tech-detect] Could not execute step: parse "https://mta-sts.hackerone.com ": invalid character " " in host name
[WRN] [tech-detect] Could not execute step: parse "https://docs.hackerone.com ": invalid character " " in host name
[WRN] [tech-detect] Could not execute step: parse "https://api.hackerone.com ": invalid character " " in host name
[WRN] [tech-detect] Could not execute step: parse "https://www.hackerone.com ": invalid character " " in host name
[WRN] [tech-detect] Could not execute step: parse "https://resources.hackerone.com ": invalid character " " in host name
[http-request] Sent for [tech-detect] to https://events.hackerone.com 
[WRN] [tech-detect] Could not execute step: parse "https://events.hackerone.com ": invalid character " " in host name
[WRN] [tech-detect] Could not execute step: parse "https://mta-sts.managed.hackerone.com ": invalid character " " in host name
[WRN] [tech-detect] Could not execute step: parse "https://mta-sts.forwarding.hackerone.com ": invalid character " " in host name
[WRN] [tech-detect] Could not execute step: parse "https://support.hackerone.com ": invalid character " " in host name
```

**Comment by dogasantos** [comment] 2020-11-03 15:18
yeap, it seems that there is a space before the newline that needs to be striped

**Comment by bauthard** [comment] 2020-11-03 15:41
@dogasantos it's an issue with `cut` command you were using that have extra space in the output, you can use the below example to get this worked, closing this issue as this is not related to nuclei. 

`cat hosts.httpx | httpx -title -content-length -status-code | awk '{print $1}' | nuclei -t technologies/tech-detect.yaml`

**Closed by bauthard** 2020-11-03 15:41 UTC
Labels: Priority: Low, Type: Bug
