### ISSUE TITLE
Is there any ways to run tags with operation AND?

### ISSUE THREAD

**Issue by breaking153** [projectdiscovery/nuclei#2252] opened 2022-07-02 05:28 UTC
i wanna run template which has both test1 and test2,--tags only support and opration.
![图片](https://user-images.githubusercontent.com/49428332/176987843-8f7de526-7140-4f03-a5e1-77623e33c24e.png)

**Comment by forgedhallpass** [comment] 2022-07-02 07:07
Duplicate of https://github.com/projectdiscovery/nuclei/issues/2251

**Comment by ehsandeep** [comment] 2022-07-02 11:02
@breaking153 this is not supported yet and will be implemented as part of https://github.com/projectdiscovery/nuclei/issues/2251

**Closed by ehsandeep** 2022-07-02 11:02 UTC
Labels: duplicate, Type: Enhancement
